### ISSUE TITLE
Scrolling issue with the side menu

### ISSUE THREAD

**Issue by swift-kim** [Samsung/tizen-docs#1039]
I'm experiencing a UI issue in Chrome and Firefox when navigating a long list of cascaded items and sub-items in the left side menu as there is no scroll bar and the height of the list exceeds my browser size.

Example: https://docs.tizen.org/application/dotnet/guides/messaging/push

Also some links under [Native Application] - [Guides] - [Watchface Complication] are broken and they are somehow duplicated under [Native Application] - [Overview] - [Watchface Complication].

**Comment by mijin85cho** [comment]
Hello.

**The LNB issue :** Known issue. We have reported this issue to the site manager and it is said that they will take some time to fix it. 

**Watchface Complication menu** : Fixed. You can check the working of the link on https://docs.tizen.org/application/native/guides/complications/overview.

**Comment by swift-kim** [comment]
@mijin85cho Do you have any update? Who's the site manager?

**Comment by mijin85cho** [comment]
@swift-kim About the LNB issue, I think you can check the progress status on https://github.sec.samsung.net/RS8-TIZENWEBSITE/docs.tizen.org/issues/247.

It looks like the fix is checked on staging site.

**Comment by swift-kim** [comment]
@mijin85cho I don't have an access to the page. Actually this issue shouldn't take more than a month for a fix.

**Comment by mijin85cho** [comment]
I left the question comment at that issue and got below answer from the person in charge today.
I copy the comment to here as you can't see the answer comment.

(In the comment, the PRD means docs.tizen.org.)

---

Dear @mijin85-cho
I made a lot of changes:

LNB usability improvement
Responsive layout
It is being deployed at DEV env https://dev-docs.stg.tizen.org/application/native/get-started/wearable/first-app/
It will be totally done this week. We can QA in next week, and then we can apply it to PRD.

**Comment by HJLeee** [comment]
> 
> 
> @swift-kim About the LNB issue, I think you can check the progress status on https://github.sec.samsung.net/RS8-TIZENWEBSITE/docs.tizen.org/issues/247.
> 
> It looks like the fix is checked on staging site.

Hello, @mijin85cho 
Any progress about this one? Asking this as I'm not able to check the private repo and the scrolling is still not fixed.

**Comment by mijin85cho** [comment]
I'm also waiting the application of the fix, but RS8-TIZENWEBSITE/docs.tizen.org/issues/247 is not updated.

@iljooo, who manages the docs.tizen.org says, there were issue reports related with this fix so the applying the fix is on holding.

**Comment by mijin85cho** [comment]
Today I got a report that the navigation bar issue fix is applied to docs.tizen.org.
I also can see the navigation menu performance is changed. Would you please check?

**Comment by swift-kim** [comment]
@mijin85cho Yes, it seems to be fixed on docs.tizen.org now. I'm not sure about the performance though. Thanks for your help!
