### ISSUE TITLE
Wrong Tizen.Net hyperlink

### ISSUE THREAD

**Issue by linuxias** [Samsung/tizen-docs#1116]
https://docs.tizen.org/application/vscode-ext/index

The Tizen.Net hyperlink in this page links to another company's page.

Please check.

**Comment by mijin85cho** [comment]
To fix this issue, #1117 is merged.

The staging link to check the fix is https://docs1.stg.tizen.org/staging/1117/application/vscode-ext/

This fix will be merged to master branch this Friday.
So I think you will be possible to check the fix on docs.tizen.org also, after this Friday.

**Comment by mijin85cho** [comment]
The fix is applied to docs.tizen.org.
You can check the https://docs.tizen.org/application/vscode-ext/index with update now.

**Comment by mijin85cho** [comment]
Hello, @linuxias

As this problem is solved, would you please close this issue?
Or, I'll close without your checking.

**Comment by mijin85cho** [comment]
I checked this issue is fixed, so I close it.
