### ISSUE TITLE
[TAU] [Wearable] No videos for examples

### ISSUE THREAD

**Issue by lslachciak** [Samsung/tizen-docs#1127]
See:
https://docs.tizen.org/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_slider.htm
https://docs.tizen.org/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_marquee.htm

Looks like filez 
https://docs.tizen.org/application/web/api/5.5/images/marquee.mp4
https://docs.tizen.org/application/web/api/5.5/images/slider.mp4
are not available

**Comment by mijin85cho** [comment]
This issue is reported as https://github.sec.samsung.net/RS8-TIZENWEBSITE/docs.tizen.org/issues/377.

**Comment by lslachciak** [comment]
Videos are working properly now. Thank you.
