### ISSUE TITLE
Docs.tizen.org issues

### ISSUE THREAD

**Issue by mijin80lee** [Samsung/tizen-docs#1135]
**Please check the hyperlink.** 

1. https://docs.tizen.org/platform/what-is-tizen/overview/ : Tizen Store 
2. https://docs.tizen.org/platform/what-is-tizen/versions/tizen-5-5-m2/ : IoT Partners
3. https://docs.tizen.org/platform/porting/system/ : dump_systemstate
4. https://docs.tizen.org/platform/porting/multimedia/ 
: http://v4l2spec.bytesex.org/spec-single/v4l2.html
5. https://docs.tizen.org/platform/porting/connectivity/
: http://linuxwireless.org/
6. https://docs.tizen.org/platform/release-notes/tizen-5-5-m1/
: http://tizen.org/feature/accessibility.grayscale
: http://tizen.org/feature/accessibility.negative
7. https://docs.tizen.org/application/dotnet/guides/nui/animation/ 
: Download the _sample file_.
**Need to report to fix this**
8. https://docs.tizen.org/application/dotnet/guides/nui/xaml/layout-define-example/
: _XAML Support for Tizen.NUI_. 
9. https://docs.tizen.org/application/web/guides/connectivity/iotcon
: IoTivity
: see _Iotivity Security_.
: see _Iotivity Security_.
10. https://docs.tizen.org/application/native/guides/ui/dali/animation/#overview
: occur in a dedicated thread
11. https://docs.tizen.org/application/native/guides/multimedia/image-edit/
: see _http://www.fourcc.org/yuv.php_
: _RGB, RGBA_ of Table: RGB pixel formats
: _UYVY, YUYV_ of Table: Packed YUV formats
: _YV16, YV12, I420, NV12, NV21_ of Table: Planar YUV formats
12. https://docs.tizen.org/application/native/guides/connectivity/iotcon/
: _IoTivity_ offers 
13. https://docs.tizen.org/application/native/guides/personal/context/
: see the _Sound Manager_
14. https://docs.tizen.org/application/tizen-studio/native-tools/manifest-text-editor/
: Manifest Element Hierarchy  (overall)
15. https://docs.tizen.org/application/tizen-studio/common-tools/emulator-features
: see _QEMU Emulator User Documentation_
16. https://docs.tizen.org/application/tizen-studio/web-tools/ide-preferences
: is _http://yourdomain/_
17. https://docs.tizen.org/application/tizen-studio/web-tools/config-editor/
: Configuration Element Hierarchy (overall)
: through the Tizen _Application_ API. (to latest)
: through the Tizen Application API. (rewrite)
: <tizen:category name=_“http://tizen.org/category/ime”_/> (delete hyperlink)
18. https://docs.tizen.org/application/tizen-studio/web-tools/web-localization
: see _Localization_
19. https://docs.tizen.org/application/vstools/tools/manifest-editor/
: Manifest Element Hierarchy (overall)

**Please check all outdated hyperlinks to https://www.w3.org/.**
1. https://docs.tizen.org/application/web/guides/w3c/w3c-overview/
: All documents of W3C/HTML5/Supplementary Features
2. https://docs.tizen.org/application/tizen-studio/web-tools/config-editor/
: see _Widget Packaging and XML Configuration_
: in the _Widget Packaging and XML Configuration guidelines_
: in the _Widget Packaging and XML Configuration guidelines_

**Please check the unnecessary sentence.**
1. https://docs.tizen.org/platform/what-is-tizen/versions/tizen-4-0-m2/
: For more information of Tizen IoT preview 1, see here.

**Please check the TOC box.**
1. https://docs.tizen.org/platform/get-started/git-repo-structure/

**Please check the style consistency.**
Font style
1. https://docs.tizen.org/platform/what-is-tizen/profiles/tv/
: Create Samsung Smart TV Web applications
2. https://docs.tizen.org/platform/what-is-tizen/versions/tizen-4-0-m2/
: Figure. Evolution of Tizen
: Figure. Tizen .NET architecture and groundwork
3. https://docs.tizen.org/application/native/api/overview/
: Figure:Required Header
: Figure:Related Feature
: Figure:Reference Structure
: Figure:Privilege

Note style
1. https://docs.tizen.org/application/dotnet/guides/nui/styling-controls-with-JSON/
: Note in the Table: View style properties affecting a push button

**Please insert the proper image.**
1. https://docs.tizen.org/application/tizen-studio/setup/install-sdk
: Click the _…_ button 
cf. advanced_conf_browse.png of https://docs.tizen.org/application/tizen-studio/setup/advanced-configuration

**Please check broken images.**
1. https://docs.tizen.org/application/web/get-started/wearable/first-app/
: Select the profile (Wearable) and version from a drop-down list and click Next.
: Select the Web Application application type and click Next.
2. https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Box.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Box.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Conformant.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Conformant.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Layout.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Layout.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Mapbuf.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Mapbuf.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Panes.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Bg.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Ctxpopup.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Label.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__List.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Radio.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Slider.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Win.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Bg.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Colorselector.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Ctxpopup.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Hoversel.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Label.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__List.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Map.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Notify.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Panel.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Photocam.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Radio.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Segment__Control.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Slider.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Spinner.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Toolbar.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Win.html
: _preview-00.png_

3. https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Button.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Check.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Datetime.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Button.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Check.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Datetime.html
: _preview-00.png, preview-01.png, preview-02.png_

4. https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Entry.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Entry.html
: _preview-00.png, preview-01.png, preview-02.png, preview-03.png_

**Please check TOC missing titles.**
1. https://docs.tizen.org/application/web/guides/connectivity/connectivity/
: Network Bearer Selection
2. https://docs.tizen.org/application/web/guides/sensors/sensors/
: Gesture Recognition
3. https://docs.tizen.org/application/web/guides/text-input/text-input/
: Voice Control
4. https://docs.tizen.org/application/dotnet/guides/connectivity/overview/
: Internet and Content Downloads
5. https://docs.tizen.org/application/native/tutorials/overview/
: Designing Your Native Application

**Please check Overview missing titles.**
1. https://docs.tizen.org/application/dotnet/guides/overview/
: OpenTK
2. https://docs.tizen.org/application/dotnet/guides/connectivity/overview/
: Connection Management
: Web view
3. https://docs.tizen.org/application/web/guides/w3c/perf-opt/performance-guide/
: JavaScript Performance Improvement
: JavaScript and CSS Minification
: jQuery Performance Improvement

**Please check the TOC tree.**
1. Media Content and Metadata, Media Content, Metadata
https://docs.tizen.org/application/dotnet/guides/multimedia/media-content-metadata/
https://docs.tizen.org/application/dotnet/guides/multimedia/media-content/
https://docs.tizen.org/application/dotnet/guides/multimedia/metadata/

**Comment by mijin85cho** [comment]
Additional issues
**HTML tag is used at hyperlink**
 - https://docs.tizen.org/application/get-started/wearable/
 - https://docs.tizen.org/application/get-started/tv/
 - https://docs.tizen.org/application/get-started/mobile/

**Please check the TOC tree**
 - https://docs.tizen.org/application/web/tutorials/process/app-dev-process/

**Comment by mijin85cho** [comment]
PR 1200 is created to fix the issues that can be controlled on docs.tizen.org.
I left some comments for other issues here.
---

**Please check the hyperlink.** 

1. https://docs.tizen.org/platform/what-is-tizen/overview/ : Tizen Store 
2. https://docs.tizen.org/platform/what-is-tizen/versions/tizen-5-5-m2/ : IoT Partners
3. https://docs.tizen.org/platform/porting/system/ : dump_systemstate
4. https://docs.tizen.org/platform/porting/multimedia/ 
: http://v4l2spec.bytesex.org/spec-single/v4l2.html
5. https://docs.tizen.org/platform/porting/connectivity/
: http://linuxwireless.org/
6. https://docs.tizen.org/platform/release-notes/tizen-5-5-m1/
: http://tizen.org/feature/accessibility.grayscale
: http://tizen.org/feature/accessibility.negative
7. https://docs.tizen.org/application/dotnet/guides/nui/animation/ 
: Download the _sample file_.
**mijin85cho : Need to report to docs manager.**
8. https://docs.tizen.org/application/dotnet/guides/nui/xaml/layout-define-example/
: _XAML Support for Tizen.NUI_. 
9. https://docs.tizen.org/application/web/guides/connectivity/iotcon
: IoTivity
: see _Iotivity Security_.
: see _Iotivity Security_.
10. https://docs.tizen.org/application/native/guides/ui/dali/animation/#overview
: occur in a dedicated thread
11. https://docs.tizen.org/application/native/guides/multimedia/image-edit/
: see _http://www.fourcc.org/yuv.php_
: _RGB, RGBA_ of Table: RGB pixel formats
: _UYVY, YUYV_ of Table: Packed YUV formats
: _YV16, YV12, I420, NV12, NV21_ of Table: Planar YUV formats
**mijin85cho : When I try the URLs by phone, I can access them. Would you please check again with out link?**
12. https://docs.tizen.org/application/native/guides/connectivity/iotcon/
: _IoTivity_ offers 
13. https://docs.tizen.org/application/native/guides/personal/context/
: see the _Sound Manager_
14. https://docs.tizen.org/application/tizen-studio/native-tools/manifest-text-editor/
: Manifest Element Hierarchy  (overall)
**mijin85cho : These links are removed by intent.**
15. https://docs.tizen.org/application/tizen-studio/common-tools/emulator-features
: see _QEMU Emulator User Documentation_
16. https://docs.tizen.org/application/tizen-studio/web-tools/ide-preferences
: is _http://yourdomain/_
17. https://docs.tizen.org/application/tizen-studio/web-tools/config-editor/
: Configuration Element Hierarchy (overall)
**mijin85cho : These links are removed by intent.**
: through the Tizen _Application_ API. (to latest)
: through the Tizen Application API. (rewrite)
: <tizen:category name=_“http://tizen.org/category/ime”_/> (delete hyperlink)
18. https://docs.tizen.org/application/tizen-studio/web-tools/web-localization
: see _Localization_
**mijin85cho : I couldn't get what is the problem. Would you please describe again?**
19. https://docs.tizen.org/application/vstools/tools/manifest-editor/
: Manifest Element Hierarchy (overall)
**mijin85cho : These links are removed by intent.**
**Please check all outdated hyperlinks to https://www.w3.org/.**
1. https://docs.tizen.org/application/web/guides/w3c/w3c-overview/
: All documents of W3C/HTML5/Supplementary Features
**mijin85cho : The updated Web API links should be confirmed by Web API team.**
2. https://docs.tizen.org/application/tizen-studio/web-tools/config-editor/
: see _Widget Packaging and XML Configuration_
: in the _Widget Packaging and XML Configuration guidelines_
: in the _Widget Packaging and XML Configuration guidelines_


**Please check the unnecessary sentence.**
1. https://docs.tizen.org/platform/what-is-tizen/versions/tizen-4-0-m2/
: For more information of Tizen IoT preview 1, see here.


**Please check the TOC box.**
1. https://docs.tizen.org/platform/get-started/git-repo-structure/


**Please check the style consistency.**
Font style
1. https://docs.tizen.org/platform/what-is-tizen/profiles/tv/
: Create Samsung Smart TV Web applications
**mijin85cho : This style is by intent. [Reference link](https://github.com/Samsung/tizen-docs/commit/a9b26a2a7d1eb5e091418553e271278b8ba6f443#diff-a709d20dab61aad39b4d3b9ea84efb37) **
2. https://docs.tizen.org/platform/what-is-tizen/versions/tizen-4-0-m2/
: Figure. Evolution of Tizen
: Figure. Tizen .NET architecture and groundwork
3. https://docs.tizen.org/application/native/api/overview/
: Figure:Required Header
: Figure:Related Feature
: Figure:Reference Structure
: Figure:Privilege

Note style
1. https://docs.tizen.org/application/dotnet/guides/nui/styling-controls-with-JSON/
: Note in the Table: View style properties affecting a push button
**mijin85cho : We can't use md tag in html tag. So the Note style in the table can't be handled. Please keep current.**
**Please insert the proper image.**
1. https://docs.tizen.org/application/tizen-studio/setup/install-sdk
: Click the _…_ button 
cf. advanced_conf_browse.png of https://docs.tizen.org/application/tizen-studio/setup/advanced-configuration



**Please check broken images.**
1. https://docs.tizen.org/application/web/get-started/wearable/first-app/
: Select the profile (Wearable) and version from a drop-down list and click Next.
: Select the Web Application application type and click Next.
2. https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Box.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Box.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Conformant.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Conformant.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Layout.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Layout.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Mapbuf.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Mapbuf.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Panes.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Bg.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Ctxpopup.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Label.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__List.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Radio.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Slider.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Win.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Bg.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Colorselector.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Ctxpopup.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Hoversel.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Label.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__List.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Map.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Notify.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Panel.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Photocam.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Radio.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Segment__Control.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Slider.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Spinner.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Toolbar.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Win.html
: _preview-00.png_
**mijin85cho : These issues should be fixed on Native API reference.**

3. https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Button.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Check.html
https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Datetime.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Button.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Check.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Datetime.html
: _preview-00.png, preview-01.png, preview-02.png_
**mijin85cho : These issues should be fixed on Native API reference.**

4. https://docs.tizen.org/application/native/api/wearable/latest/group__Elm__Entry.html
https://docs.tizen.org/application/native/api/mobile/latest/group__Elm__Entry.html
: _preview-00.png, preview-01.png, preview-02.png, preview-03.png_
**mijin85cho : These issues should be fixed on Native API reference.**


**Please check TOC missing titles.**
1. https://docs.tizen.org/application/web/guides/connectivity/connectivity/
: Network Bearer Selection
2. https://docs.tizen.org/application/web/guides/sensors/sensors/
: Gesture Recognition
3. https://docs.tizen.org/application/web/guides/text-input/text-input/
: Voice Control
4. https://docs.tizen.org/application/dotnet/guides/connectivity/overview/
: Internet and Content Downloads
5. https://docs.tizen.org/application/native/tutorials/overview/
: Designing Your Native Application

**Please check Overview missing titles.**
1. https://docs.tizen.org/application/dotnet/guides/overview/
: OpenTK
**mijin85cho : We have separate OpenTK section above of the list. So please keep the current. [Reference link](https://github.com/Samsung/tizen-docs/pull/485/files)**
2. https://docs.tizen.org/application/dotnet/guides/connectivity/overview/
: Connection Management
: Web view
3. https://docs.tizen.org/application/web/guides/w3c/perf-opt/performance-guide/
: JavaScript Performance Improvement
: JavaScript and CSS Minification
: jQuery Performance Improvement


**Please check the TOC tree.**
1. Media Content and Metadata, Media Content, Metadata
https://docs.tizen.org/application/dotnet/guides/multimedia/media-content-metadata/
https://docs.tizen.org/application/dotnet/guides/multimedia/media-content/
https://docs.tizen.org/application/dotnet/guides/multimedia/metadata/

**Comment by mijin80lee** [comment]
@mijin85cho 
Thank you for your comment and there are no more issues.
And if the issue below is resolved, I will close this issue. 
-Outdated hyperlinks to https://www.w3.org/

One thing,  Native API ref. broken image issues overlap with #1176, I'll move them to  #1176. 
Thank you.
