### ISSUE TITLE
Need to update SDK prerequisite guide

### ISSUE THREAD

**Issue by poiema72** [Samsung/tizen-docs#1222]
https://docs.tizen.org/application/tizen-studio/setup/prerequisites/

From above, current Tizen Studio supports only Windows 10.

However, T-trace guide includes window 7/8 like below.

`To use the T-trace in Windows® 8/7, you must install a Python 2.7.X version:
On the Python Web site, download the appropriate Python version for your hardware and Windows® version.
Run the downloaded installer file and follow the displayed instructions.`

I think that it needs to be revised.

**Comment by mijin85cho** [comment]
Thanks for the issue report.

Related with this, https://github.com/Samsung/tizen-docs/pull/1223 is merged.

We will merge the update to live branch later, and it will update docs.tizen.org.

**Comment by mijin85cho** [comment]
As the fix for this PR is merged, I close this PR. Thanks for the report.
