### ISSUE TITLE
TableView and TextLabel code examples from NUI guide don't work

### ISSUE THREAD

**Issue by MathewP1** [Samsung/tizen-docs#1229]
### TableView

- [TableView](https://docs.tizen.org/application/dotnet/guides/nui/tableview/) example is missing cast to uint, now it won't build.

### Text
[Text](https://docs.tizen.org/application/dotnet/guides/nui/text/): This code example:
```
label.FontFamily = "FreeSerif";

PropertyMap fontStyle = new PropertyMap();
fontStyle.Add("weight", new PropertyValue(FontWeightType.Bold));
fontStyle.Add("slant", new PropertyValue(FontSlantType.Italic));
label.FontStyle = fontStyle;
label.PointSize = 12.0f;
```
doesn't work. _cannot convert from 'Tizen.NUI.FontWeightType' to 'Tizen.NUI.Size2D'_

**Comment by mijin85cho** [comment]
Hello, @Seoyeon2Kim and @JoogabYun.

Would you please check this issue report on TableView and Text?
If other person is in charge of these pages, please let that person also know.

**Comment by Seoyeon2Kim** [comment]
Hello, I'll handle this issue.

**Comment by mijin85cho** [comment]
The PR #1232 for this issue was merged into master branch.

If the fix is synced into live branch, the docs.tizen.org will be updated, too.
Thanks for the report.
