### ISSUE TITLE
.NET Application Samples Issues

### ISSUE THREAD

**Issue by mijin80lee** [Samsung/tizen-docs#1269]
### Please check and modify the link below.
(https://developer.tizen.org/ to https://docs.tizen.org/)

1. https://docs.tizen.org/application/dotnet/samples/appfw/overview/ (Mobile)
**(M) Badges**
Native version
https://developer.tizen.org/development/sample/native/AppFW/Badges to https://docs.tizen.org/development/sample/native/AppFW/Badges
**(M) Preference**
Native version
https://developer.tizen.org/development/sample/native/AppFW/Preference to https://docs.tizen.org/development/sample/native/AppFW/Preference

2. https://docs.tizen.org/application/dotnet/samples/appfw/overview/ (Wearable)
**(W) Alarm**
Native version
https://developer.tizen.org/development/sample/native/UI/%28Circle%29_Alarm to https://docs.tizen.org/development/sample/native/UI/(Circle)_Alarm
Web version
https://developer.tizen.org/development/sample/web/UI/Alarm_UI to https://docs.tizen.org/development/sample/web/UI/Alarm_UI
**(W) AppControl**
Native version
https://developer.tizen.org/development/sample/native/AppFW/Application_control to https://docs.tizen.org/development/sample/native/AppFW/Application_control
Web version
https://developer.tizen.org/development/sample/web/Application/App_Control to https://docs.tizen.org/development/sample/web/Application/App_Control
**(W) AppInformation**
Native version
https://developer.tizen.org/development/sample/native/AppFW/App-common to https://docs.tizen.org/development/sample/native/AppFW/App-common
**(W) BadgeCounter**
Web version
https://developer.tizen.org/development/sample/web/Application/Badges to https://docs.tizen.org/development/sample/web/Application/Badges
**(W) MessagePortSampleApp**
Native version
https://developer.tizen.org/development/sample/native/AppFW/%28Tutorial%29_Message_Port to https://docs.tizen.org/development/sample/native/AppFW/%28Tutorial%29_Message_Port
**(W) ServiceApp**
Native version
https://developer.tizen.org/development/sample/native/AppFW/%28Tutorial%29_Service_Application to https://docs.tizen.org/development/sample/native/AppFW/%28Tutorial%29_Service_Application
Service Application
https://developer.tizen.org/development/guides/native-application/application-management/applications/service-application to https://docs.tizen.org/application/native/guides/applications/service-app/
Service Application
https://developer.tizen.org/development/guides/web-application/application-management/applications/service-application to https://docs.tizen.org/application/web/guides/applications/service-app/
3. https://docs.tizen.org/application/dotnet/samples/general/overview/ (Wearable)
**(W) VoiceMemo**
Native version
https://developer.tizen.org/development/sample/native/UI/%28Circle%29_Voice_Memo to https://docs.tizen.org/development/sample/native/UI/(Circle)_Voice_Memo
Web version
https://developer.tizen.org/development/sample/web/UI/Voice_Memo_UI to https://docs.tizen.org/development/sample/web/UI/Voice_Memo_UI
4. https://docs.tizen.org/application/dotnet/samples/ui/overview/ (Mobile)
**(M) Calculator**
Web version
https://developer.tizen.org/development/sample/web/General/Calculator to https://docs.tizen.org/development/sample/web/General/Calculator_M
5. https://docs.tizen.org/application/dotnet/samples/ui/overview/ (Wearable)
**(W) Calculator**
Native version
https://developer.tizen.org/development/sample/native/UI/%28Circle%29_Calculator to https://docs.tizen.org/development/sample/native/UI/%28Circle%29_Calculator
Web version
https://developer.tizen.org/development/sample/web/General/Calculator_1 to https://docs.tizen.org/development/sample/web/General/Calculator_W
**(W) RotaryTimer**
Native version
https://developer.tizen.org/development/sample/native/UI/Rotary_Timer to https://docs.tizen.org/development/sample/native/UI/Rotary_Timer
Web version
https://developer.tizen.org/development/sample/web/General/Rotary_Timer to https://docs.tizen.org/development/sample/web/General/Rotary_Timer
**(W) XStopWatch**
Native version
https://developer.tizen.org/development/sample/native/UI/%28Circle%29_Stopwatch to https://docs.tizen.org/development/sample/native/UI/%28Circle%29_Stopwatch
6. https://docs.tizen.org/application/dotnet/samples/watch/overview/ (Wearable)
**(W) AmbientWatch**
Native version
https://developer.tizen.org/development/sample/native/Watch/Ambient_Analog_Watch to https://docs.tizen.org/development/sample/native/Watch/Ambient_Analog_Watch
Web version
https://developer.tizen.org/development/sample/web/Watch/Ambient_Watch to https://docs.tizen.org/development/sample/web/Watch/Ambient_Watch
**(W) ChronographWatch**
Native version
https://developer.tizen.org/development/sample/native/Watch/Chronograph_Watch to https://docs.tizen.org/development/sample/native/Watch/Chronograph_Watch
Web version
https://developer.tizen.org/development/sample/web/Watch/Chronograph_Watch to https://docs.tizen.org/development/sample/web/Watch/Chronograph_Watch
**(W) ClassicWatch**
Native version
https://developer.tizen.org/development/sample/native/Watch/Classic_Watch to https://docs.tizen.org/development/sample/native/Watch/Classic_Watch
Web version
https://developer.tizen.org/development/sample/web/Watch/Classic_Watch to https://docs.tizen.org/development/sample/web/Watch/Classic_Watch
**(W) WeatherWatch**
Native version
https://developer.tizen.org/development/sample/native/Watch/Weather_Watch to https://docs.tizen.org/development/sample/native/Watch/Weather_Watch
Web version
https://developer.tizen.org/development/sample/web/Watch/Weather_Watch to https://docs.tizen.org/development/sample/web/Watch/Weather_Watch

**Comment by mijin85cho** [comment]
Hello, I created PR #1275 to fix this issue.
Would you please check it with the stg URL?

**Comment by mijin80lee** [comment]
@mijin85cho  Thank you for the PR. 
I reviewed all and left comment that you could check.
