### ISSUE TITLE
Driver requirement needs to be revised.

### ISSUE THREAD

**Issue by poiema72** [Samsung/tizen-docs#1291]
In https://docs.tizen.org/application/tizen-studio/setup/prerequisites/

Ubuntu OS requirement is like below.

`18.04/16.04`

However, `Driver` in the `Emulator Requirements`, it is mentioned like below.

`In 16.04 and 14.04, the Intel driver version must be 8.0.1 or higher.`

Above part needs to be updated.

**Comment by mijin85cho** [comment]
Thanks for the report. I created PR https://github.com/Samsung/tizen-docs/pull/1292 for this issue.

**Comment by mijin85cho** [comment]
As the https://github.com/Samsung/tizen-docs/pull/1292 for this issue is closed, I also close this issue.
Thanks for the report.
