### ISSUE TITLE
Application marketplace link issue

### ISSUE THREAD

**Issue by poiema72** [Samsung/tizen-docs#1300]
https://docs.tizen.org/platform/what-is-tizen/overview/

From above page, as for the application marketplace, it seems that Tizen Store link needs to be revised with appropriate ones.

In addition to this, as for wearable, not `Galaxy Watch Active 2` but `Galaxy Watch Active2`. And we can add `Galaxy Watch3` also.

**Comment by journey2w** [comment]
Thank you for reporting this issue.
Resolved on PR #1321.
