### ISSUE TITLE
Galaxy watch model issue

### ISSUE THREAD

**Issue by poiema72** [Samsung/tizen-docs#1301]
From this link (https://docs.tizen.org/platform/what-is-tizen/profiles/wearable/), under `Figure: Wearable Samsung Galaxy Watch devices`, `Saamsung Galaxy Active 2` needs to be revised to `Samsung Galaxy Watch Active2`.

**Comment by journey2w** [comment]
@poiema72 
I couldn't find any issue about the model name.
When I see the `Samsung Galaxy Watch Active2`.

I found out the following paragraph is outdated. I will fix it soon.
```
From the Samsung Gear 2 Neo to the current Gear S3, all wearable devices have their own characteristics that boast their functionalities. 
...
```
