### ISSUE TITLE
Tizen 6.0 link issues

### ISSUE THREAD

**Issue by mijin80lee** [Samsung/tizen-docs#1313]
### .NET Application
https://docs.tizen.org/application/dotnet/guides/connectivity/smartcard/
see the SimAlliance
### Web Application(incl. API Reference)
**It does not go to the exact inner link location**
https://docs.tizen.org/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_Navigation.htm
: pop() of Method table
https://docs.tizen.org/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_PanelChanger.htm
: 1. Default selectors
https://docs.tizen.org/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_drawer.htm
: 3. HTML Example with Options
### Native Application
**페이지가 작동하지 않습니다.**
https://docs.tizen.org/application/native/guides/connectivity/smartcard/
see the SimAlliance
(ref. https://trustedconnectivityalliance.org/simalliance-becomes-trusted-connectivity-alliance/)
### Tizen Studio
**Check the URL.**
Mobile and wearable going to the same location. 
https://docs.tizen.org/application/tizen-studio/native-tools/ui-builder/component-attributes
see the related guides (mobile and wearable)
https://docs.tizen.org/application/native/guides/ui/efl/ui-components
-> https://docs.tizen.org/application/native/guides/ui/efl/mobile/ui-components/
-> https://docs.tizen.org/application/native/guides/ui/efl/wearable/ui-components/
### ETC
**404 Not found Error**
https://docs.tizen.org/partners/iot-partners/sdt_som/
see https://www.sigma-delta.tech/sdt-a7x2-m4
**Path not found**
https://docs.tizen.org/platform/porting/graphics-and-ui/
https://cgit.freedesktop.org/mesa/mesa/tree/docs/specs/WL_bind_wayland_display.spec

###  Fixed by PR https://github.com/Samsung/tizen-docs/pull/1330
**The first letter is not capitalized.**
~https://docs.tizen.org/application/web/api/6.0/device_api/mobile/tizen/cordova/console.html
the Console module~

### Fixed by PR https://github.com/Samsung/tizen-docs/pull/1334
**.NET Application**
**404 Not Found**
~https://docs.tizen.org/application/dotnet/get-started/nui/quickstart/
see the TextLabel.
https://docs.tizen.org/application/dotnet/guides/opentk/create-app-skiasharp/
There is a OpenTK sample application
https://docs.tizen.org/application/dotnet/guides/opentk/create-app-skiasharp/
see Tizen-CSharp-Samples
https://docs.tizen.org/application/dotnet/guides/security/tee-client/
on the GlobalPlatform® TEE Client API~
**Web Application(incl. API Reference)**
**Link to https://developer.tizen.org/, need to check**
~https://docs.tizen.org/application/web/tutorials/process/app-dev-process/
see Hybrid Web App sample (in mobile and wearable applications), Hybrid Service sample,
see Tizen Store Overview
https://docs.tizen.org/application/web/guides/tau/creating-animation/
from the UIComponent~
**The item (title) in the table should be changed to "Node".** 
~https://docs.tizen.org/application/web/api/5.5/wearable_widget/web_widget.html
: HTMLCollection(The second HTMLCollection) -> Node~
**Native Application**
**Link to https://developer.tizen.org/, need to check**
~https://docs.tizen.org/application/native/guides/ui/efl/component-custom/
within the EFL Core samples
https://docs.tizen.org/application/native/guides/ui/efl/accessibility-implementation/
use the mobile native UI Components
https://docs.tizen.org/application/native/guides/personal/context/
see the Contacts guide.
see the Wi-Fi guide.
see Package ID and Application ID.~
**404 Not Found**
~https://docs.tizen.org/application/native/guides/personal/context/
see the Media Content and Metadata guide.~
**Tizen Studio**
**Check the API version.** 
~https://docs.tizen.org/application/tizen-studio/native-tools/ui-builder/convert-projects/
Elementary window (in mobile and wearable applications)
Naviframe (in mobile and wearable applications)~
**ETC**
**It does not go to the exact inner link location**
~https://docs.tizen.org/application/vscode-ext/web/
Tizen Web: Build Tizen App
Tizen Web: Debug Tizen App
Tizen Web: Install Tizen App
Tizen Web: Make Exclude Build List
Tizen Web: Run Tizen App~
### Decided to maintain the current status
**Web** Application
**Outdated contents(https://www.w3.org/)**
(Please check the entire page for links that do not specify the location.)
https://docs.tizen.org/application/web/
the   guidelines of W3C Widget Packaging and XML Configuration
https://docs.tizen.org/application/web/tutorials/web-runtime/
https://docs.tizen.org/application/web/tutorials/sign-certificate/
the XML Digital Signatures for Widgets specified by W3C
https://docs.tizen.org/application/web/guides/text-input/input-method/
according to the Widget packaging guidelines
https://docs.tizen.org/application/web/guides/text-input/input-device/
the DOM Level 3 KeyboardEvent key Values
the Media Controller Keys
https://docs.tizen.org/application/web/guides/w3c/device/battery/
all 'the BatteryManager interface' in 'wearable applications' 
https://docs.tizen.org/application/web/guides/w3c/device/device-orientation/
https://docs.tizen.org/application/web/guides/w3c/graphics/canvas/
'CanvasRenderingContext2D interface' in 'wearable applications' 
https://docs.tizen.org/application/web/guides/w3c/multimedia/media-capture/
the HTMLInputElement
https://docs.tizen.org/application/web/guides/w3c/multimedia/webaudio/
https://docs.tizen.org/application/web/guides/w3c/communication/web-messaging/
https://docs.tizen.org/application/web/guides/w3c/communication/xmlhttprequest/
https://docs.tizen.org/application/web/guides/w3c/storage/file/
https://docs.tizen.org/application/web/guides/w3c/storage/indexdb/
https://docs.tizen.org/application/web/guides/w3c/storage/web-storage/
https://docs.tizen.org/application/web/guides/w3c/security/cors/
https://docs.tizen.org/application/web/guides/w3c/perf-opt/web-workers/
'multi-thread Web workers' in 'wearable applications' 
https://docs.tizen.org/application/web/guides/w3c/location/geolocation/
https://docs.tizen.org/application/web/guides/w3c/ui/flexible/
https://docs.tizen.org/application/web/guides/w3c/ui/multi/
using a pseudo-algorithm
https://docs.tizen.org/application/web/guides/w3c/ui/text-module/
see the Property index
https://docs.tizen.org/application/web/guides/w3c/ui/basic-ui/
The pseudo-class selectors
https://docs.tizen.org/application/web/guides/w3c/ui/font/
see the Property index
https://docs.tizen.org/application/web/guides/w3c/ui/woff/
the @font-face rule
https://docs.tizen.org/application/web/api/6.0/device_api/mobile/tizen/cordova/device-motion.html
Original documentation: Cordova Accelerometer.
https://docs.tizen.org/application/web/api/6.0/w3c_api/w3c_api_m.html
https://docs.tizen.org/application/web/api/6.0/wearable_widget/web_widget.html
https://docs.tizen.org/application/web/api/6.0/w3c_api/w3c_api_w.html
https://docs.tizen.org/application/web/api/6.0/device_api/tv/tizen/tvinputdevice.html
in the DOM Level 3 KeyboardEvent key Values specification
The Media Controller Keys
https://docs.tizen.org/application/web/api/6.0/w3c_api/w3c_api_tv.html
**Unofficial draft**
https://docs.tizen.org/application/web/api/6.0/w3c_api/w3c_api_w.html
Web Speech (Partial)
https://docs.tizen.org/application/tizen-studio/web-tools/config-editor/
see Widget Packaging and XML Configuration
in the Widget Packaging and XML Configuration guidelines
**'페이지가 작동하지 않습니다.'**
https://docs.tizen.org/application/web/guides/w3c/graphics/canvas/
http://webglstats.com/
**This package has been deprecated**
https://docs.tizen.org/application/web/api/6.0/device_api/mobile/tizen/cordova/console.html
Cordova Console
(https://www.npmjs.com/package/cordova-plugin-console)
**Native** Application
**Outdated contents(https://www.w3.org/)**
https://docs.tizen.org/application/native/tutorials/details/sign-certificate/
the XML Digital Signatures for Widgets specified by W3C
**Tizen Studio**
**Outdated contents(https://www.w3.org/)**
https://docs.tizen.org/application/tizen-studio/web-tools/config-editor/
see Widget Packaging and XML Configuration
in the Widget Packaging and XML Configuration guidelines

**Comment by mijin85cho** [comment]
For the broken link issues, I raised PR https://github.com/Samsung/tizen-docs/pull/1334.

Also, I have questions to below two items.

### Web Application
- https://docs.tizen.org/application/web/tutorials/process/setting-properties/
  see Tizen Store Overview
  **=> Would you please check the string? I can't find "see Tizen Store Overview" in this page.**
- https://docs.tizen.org/application/web/guides/text-input/input-method/
  see Configuration Elements and Extending Configuration Elements
  **=> Would you please add some description about this issue? These links are working.**

**Comment by mijin80lee** [comment]
@mijin85cho I'm sorry for confusing.
I modified it as follows. Please refer to it.

**Link to https://developer.tizen.org/, need to check**
https://docs.tizen.org/application/web/tutorials/process/app-dev-process/
see Tizen Store Overview
**Outdated contents(https://www.w3.org/)**
https://docs.tizen.org/application/web/guides/text-input/input-method/
according to the Widget packaging guidelines

**Comment by mijin85cho** [comment]
@mijin80lee Thanks for the update.

>**Link to https://developer.tizen.org/, need to check**
>https://docs.tizen.org/application/web/tutorials/process/app-dev-process/
>see Tizen Store Overview

=> The link is https://developer.tizen.org/distribution/tizen-store-overview.
As the pages under "Distribution" category is not moved into docs.tizen.org. So we can keep current link.

**Comment by mijin80lee** [comment]
Please refer to #1401.
