### ISSUE TITLE
Profile description needs to be revised.

### ISSUE THREAD

**Issue by poiema72** [Samsung/tizen-docs#1326]
https://docs.tizen.org/platform/what-is-tizen/overview/

From the link above. I think that it depends on 'IoT' is profile or not, but the description below needs to be revised.

**Tizen is built to work on diverse devices, and profiles are defined accordingly. Currently, 3 profiles are supported:

Wearable
TV
Mobile
IoT**

3 profiles and 4 list items seem to be not matched. (I think that we need to consider this link also https://docs.tizen.org/platform/what-is-tizen/profiles/iot/ based on whether IoT is profile or not.)

**Comment by mijin85cho** [comment]
Thanks for the report. With PR https://github.com/Samsung/tizen-docs/pull/1333, the sentence is updated.
