### ISSUE TITLE
WebView not run on TV Extension Image 6.0

### ISSUE THREAD

**Issue by thongdesti** [Samsung/tizen-docs#1396]
I test WebView with Tizen TV 6.0 follow this manual but it not run
https://docs.tizen.org/application/dotnet/guides/connectivity/webview/
It run on Tizen TV 5.5 and 4.0

**Comment by mijin85cho** [comment]
I asked @younghajung to check this issue.

**Comment by younghajung** [comment]
Sorry for the late reply.
As a result of checking with TV SDK part, we can not guarantee execution because it is not officially supporting WebView in TV SDK.
Thank you.

**Comment by kcm1992122** [comment]
Hello, How are you?
Can you teach me how to get back tv extension 6.0?

**Comment by thongdesti** [comment]
> Hello, How are you? Can you teach me how to get back tv extension 6.0?

https://developer.samsung.com/smarttv/develop/tools/tv-extension/archive.html

**Comment by kcm1992122** [comment]
Thank you.
