### ISSUE TITLE
Remote control keys for applications 

### ISSUE THREAD

**Issue by Azghour-Saad** [Samsung/tizen-docs#1486]
Hi,

i exécuté this source code in my JavaScript file

      if(keyEvent.keyCode === keyCode.KEY_DOWN) { 
           // this  keyEvent.keyCode is  working === 40
	        console.log("The CHANNEL DOWN was good", keyEvent.keyCode);

             // but remote contrôle here dosn't work and not goes down  
	        tizen.tvinputdevice.registerKey("KEY_DOWN");
       }
Best regards,

**Comment by annie-samsung** [comment]
@Azghour-Saad, could you let us know which topic are you referring to on docs.tizen.org?

**Comment by Azghour-Saad** [comment]
Hi @annie-samsung,

https://developer.samsung.com/smarttv/develop/guides/user-interaction/remote-control.html
https://www.tizen.org/tv/web_device_api/tvinputdevice

**Comment by annie-samsung** [comment]
> https://developer.samsung.com/smarttv/develop/guides/user-interaction/remote-control.html

@Azghour-Saad, thanks for providing us with the links.
https://developer.samsung.com/smarttv/develop/guides/user-interaction/remote-control.html - We do not manage the content on developer.samsung.com, you could try reaching out through the support page: https://developer.samsung.com/support

https://www.tizen.org/tv/web_device_api/tvinputdevice - This content is outdated, you can find the updated API reference here 
https://docs.tizen.org/application/web/api/latest/device_api/tv/tizen/tvinputdevice.html

**Comment by Azghour-Saad** [comment]
Hi, @annie-samsung 

Thanks a lot 👍
