### ISSUE TITLE
Document for dotnet to build a widget or watch face

### ISSUE THREAD

**Issue by zandiarash** [Samsung/tizen-docs#1583]
Hello dear developers
Please add a document and a sample for Dotnet to build a widget or watch face for wearable devices.
There is web version with JavaScript but there is nothing for **c#**
Actually I want to make a solar calendar and show on the watch screen. I have the algorithm and `c#` codes but I don't know how to show the calendar over the watch face permanently.
Someone please send me a documentation and help me.
Therefore I will share my calendar widget here in GitHub for everyone.
Thanks.

**Comment by WonyoungChoi** [comment]
Documents related to Watch can be found at https://developer.samsung.com/tizen/About-Tizen.NET/Tizen.NET.html.

**Comment by zandiarash** [comment]
Dear @WonyoungChoi Thanks for the link
But it doesn't actually helped me.
I want to  build a widget or watch face for wearable devices which always show the solar calendar on the screen

**Comment by JoonghyunCho** [comment]
Hi, hope this helps :)
Widget: https://github.com/rookiejava/sdc2019-tizen-net/tree/master/demo/GalaxyWatch/PrettyWeatherWidget
WatchFace: https://github.com/rookiejava/sdc2019-tizen-net/tree/master/demo/GalaxyWatch/WatchFaceSDC2019

**Comment by JoonghyunCho** [comment]
There are also some docs for watch face  and widgets.
guide: https://developer.samsung.com/tizen/Galaxy-Watch/guides/creating-a-watchface.html
tutorial: http://tizenschool.org/tutorial/147/contents/1
widget blog: https://developer.samsung.com/tizen/blog/en-us/2019/12/02/build-a-widget-for-galaxy-watch

**Comment by zandiarash** [comment]
Thanks alote dear @JoonghyunCho  your links are very helpful, I appreciate it.

**Comment by mijin85cho** [comment]
I close this issue, as it seems the question is resolved.

Thanks for the answers, @WonyoungChoi and @JoonghyunCho !
