### ISSUE TITLE
[NUI] Document the new tags and attributes in Markup

### ISSUE THREAD

**Issue by shrouqsabah** [Samsung/tizen-docs#1618]
Hello dears,

We need to document the added tags and attributes into markup.

Tags and attributes for each tag:
- BOLD
- ITALIC
- UNDERLINE
   - COLOR
   - HEIGHT
   - TYPE
   - DASH_GAP
   - DASH_WIDTH
- BACKGROUND
   - COLOR
- STRIKETHROUGH
   - COLOR
   - HEIGHT
- CHARACTER_SPACING
   - VALUE
- SPAN
   - FONT_FAMILY
   - FONT_SIZE
   - FONT_WEIGHT
   - FONT_WIDTH
   - FONT_SLANT
   - TEXT_COLOR
   - BACKGROUND_COLOR
   - UNDERLINE_COLOR
   - UNDERLINE_HEIGHT
   - UNDERLINE_TYPE
   - UNDERLINE_DASH_GAP
   - UNDERLINE_DASH_WIDTH
   - STRIKETHROUGH_COLOR
   - STRIKETHROUGH_HEIGHT
   - CHARACTER_SPACING_VALUE
- PARAGRAPH
   - ALIGN
- EMBEDDED_ITEM
- ANCHOR

For more details, please check DALi code:
https://review.tizen.org/gerrit/c/platform/core/uifw/dali-toolkit/+/272869/4/dali-toolkit/internal/text/markup-tags-and-attributes.h 

Place of update is: https://docs.tizen.org/application/dotnet/guides/nui/text/#use-markup-styling-to-style-textlabel

Thanks,

**Comment by mijin85cho** [comment]
PR #1625 was merged, and applied to https://docs.tizen.org/application/dotnet/guides/user-interface/nui/text/.

So, I close this issue.
