### ISSUE TITLE
Outdated information in flashing-rpi.md

### ISSUE THREAD

**Issue by swift-kim** [Samsung/tizen-docs#1825]
https://docs.tizen.org/platform/developing/flashing-rpi/

The document says

> fusing script is same for RPI3 and RPI4

but according to https://review.tizen.org/git/?p=platform/kernel/u-boot.git;a=commit;h=5e86145ca483ee2709a661720be038a31fdb25a1, it doesn't seem the case.

**Comment by swift-kim** [comment]
그런데 실제로 테스트해보니 `sd_fusing_rpi4.sh`는 작동을 안 합니다. 스크립트를 통해서 Tizen 7.0 이미지를 구웠는데 모니터에 아무 것도 나타나지 않네요. 오히려 RPi4도 기존의 `sd_fusing_rpi3.sh`를 써야 되는 것 같네요. 이 부분은 스크립트 제작자의 확인이 필요할 것 같습니다.

**Comment by swift-kim** [comment]
번외로 IoT-headed profile은 아직도 문제가 많네요. UI가 바뀌었던 Tizen 6.0까지는 그려러니 했는데, 6.5에 이어 7.0까지도 이게 과연 정식 릴리즈?라는 의문이 들 정도입니다.

처음 부팅하고 첫 화면부터 텍스트 크기는 작아서 안 보이고 (Smart Monitor M5, Full HD), "환영합니다" 메시지 밑에는

> There should be some description or information about Tizen IoT.

이것만 네 줄이 뜨는데 흐음.. 글쎄요. 다음 릴리즈에서는 profile도 통합될 텐데 제대로 된 검증이 필요해 보입니다. 이런 부분들이 모여 플랫폼의 신뢰성을 떨어트리는 것 같습니다.

**Comment by jh80chung** [comment]
> 그런데 실제로 테스트해보니 `sd_fusing_rpi4.sh`는 작동을 안 합니다. 스크립트를 통해서 Tizen 7.0 이미지를 구웠는데 모니터에 아무 것도 나타나지 않네요. 오히려 RPi4도 기존의 `sd_fusing_rpi3.sh`를 써야 되는 것 같네요. 이 부분은 스크립트 제작자의 확인이 필요할 것 같습니다.

@swift-kim 
sd_fusing_rpi3.sh script로 rpi3/4 둘다 동작시킬수 있습니다. sd_fusing_rpi4는 A/B partition을 지원하기 위해 GPT partition을 지원하기 위해 추가되어있습니다. sd_fusing_rpi4 script를 사용하기위해서는 eeprom을 업데이트해야하며 해당 방법이 복잡하여, official하게 사용관련 가이드를 업데이트하지 않았습니다.

현재 Tizen에서 개발되고 있는 타겟은 괜장히 오래전에 구매해서 sd_fusing_rpi4.sh를 official하게 가이드를 하면 모든 개발자들이 개별적으로 업데이트를 진행해야하며 개발에 혼란을 야기할수있어 sd_fusing_rpi3.sh를 계속 유지하고 있습니다. 

참고로, 제가 sd_fusing_rpi4.sh로 가이드 업데이트를 한곳은 없는걸로 알고있습니다.

**Comment by swift-kim** [comment]
@jh80chung 답변 감사합니다. 스크립트 실행 시 "Only Raspberry Pi3 downloader" 라는 이름이 표시되고 commit 메시지에도 비슷하게 언급되어 있어서 확인 요청드렸습니다.

**Comment by jh80chung** [comment]
> 
@swift-kim 해당 comment 감사합니다. 혼란을 야기시킬수 있는 부분인것 같습니다.
초기에 rpi3로만 개발될때 생성한 script였었는데..해당 부분은 수정하는게 좋을거 같아보이네요..추후에 수정하도록 하겠습니다. 리뷰 감사합니다.

**Comment by swift-kim** [comment]
네 알겠습니다.

그밖의 문제는 다른 경로를 통해 처리하겠습니다.
