### ISSUE TITLE
URL link error in /tizen-studio

### ISSUE THREAD

**Issue by ck11a** [Samsung/tizen-docs#190]
[/common-tools/emulator.md]
OpenGL® ES acceleration **(It does not jump to that content.)**

[/extension-sdk/in-app-purchase.md]
Web
native
Web

[/extension-sdk/inmovi.md]
Unity documentation

[/native-tools/component-attributes.md]
UI container
panel
panes
supported properties **(It does not jump to that content.)**
colorselector
flipselector
gengrid
hoversel
spinner
toolbar
Custom UI Component

[/native-tools/managing-projects.md]
Device Manager 

[/native-tools/resource-manager.md]
mobile

[/native-tools/ui-builder-conversion.md]
mobile
wearable

[/native-tools/ui-builder-customcomponent.md]
EDC Editor
Layouting with EDC
Group Block
Program Block
Part Block
Color Classes Block
Normal state default icon
Mouseover state default icon
Select state default icon
Add Custom UI Component button
Event plus icon
Event arrow icon

[/native-tools/ui-builder-databind.md]
Project Wizard

[/platform-tools/overview.md]
https://developer.tizen.org/development/tizen-studio/download

[/rt-ide/getting-started/install.md]
Updating Tizen Studio 
Configuring the Package Manager

[/rt-ide/getting-started/overview.md
Install the Tizen Studio for RT
Manage the project
Flash the project
Use the serial terminal
Debug the project

[/rt-ide/smartthings-ext/build-project.md]
Build icon

[/rt-ide/smartthings-ext/create-project.md]
Creating a Project

[/rt-ide/smartthings-ext/manage-certificate.md]
SmartThings Certificate Manager
Inputting data to the Certificate Generation Dialog
Creating a certificate in the Certificate Generation Dialog

[/rt-ide/smartthings-ext/overview.md
Create a SmartThings™ project
Build the SmartThings™ project
Manage SmartThings™ certificates
Manage devices and resources

[/web-tools/config-editor.md]
wearable  **(<<tizen:account/>> It does not jump to that content.)**
mobile or wearable **(<<tizen:appdefined-privilege>>)**
mobile or wearable **(<<tizen:application>>)**
mobile or wearable **(<<tizen:provides-appdefined-privilege>>)**
wearable **(<<tizen:profile>>)**
wearable **(<<tizen:setting>>)**
mobile or wearable **(<<tizen:trust-anchor>>)**
Application Information and Controls
W3C element **(It does not jump to that content.)**
Application Information and Controls
<<tizen:widget-label/>> **(It does not jump to that content.)**
<<tizen:widget-content/>> 
<<tizen:widget-metadata/>> 
<<tizen:widget-size/>>
set the `` attribute to enable 
background category
<<tizen:content/>> **(It does not jump to that content.)**
<<tizen:name/>>
<<tizen:icon/>>
<<tizen:description/>> 
<<tizen:metadata/>>
<<tizen:category/>>

[/web-tools/ide-preferences.md]
http://yourdomain/

[/web-tools/managing-projects.md]
Certificate Registration
Device Manager 

[/web-tools/privilege-checker.md]
privilege

[/web-tools/project-wizard.md]
Web Application 
Native Application

[/index.md]
Release Notes

**Comment by mijin85cho** [comment]
Adding newly found issues
[/native-tools/ui-builder/custom-ui-component.md]
line 177 : Image missing (pal_custom_add_nor.png)
line 191 : Table for "The following table lists error messages that can occur when adding a custom UI component." is broken

**Comment by journey2w** [comment]
Fixed on PR #200.

**Comment by mijin85cho** [comment]
Adding newly found issues based on PR #200 

[/native-tools/ui-builder/multiple-screen.md]
**line 15** : The sub list items are crumpled as one line. `File types – images, EDJ, text, video, and audioStrings for localization`
Also the separated lines in the note are merged as one line. `When you support multiple screens...`.
**line 71** :  The separated lines are merged as one line. `Landscape: ...` and `Portrait: ...`
**line 82** : Broken link `Applications`. It looks `../../../native/guides/app-management/applications.md` is correct
**line 85** : Broken link `automatic scaling`. It looks `../../../native/guides/ui/efl/multiple-screens.md` is correct 
**line 101** : Broken link `Localizing Applications`. It looks `../po-file-editor.md` is correct 
**line 149** : Lines should be separated. `If there is no default resource, ...`
**line 190** :  Lines should be separated. `Open the **Screen Configurator** window, ...`
**line 194** : The list and sub list are broken. 
**line 219** : Lines should be separated. `Open the **When the size of the UI component ...`

[/native-tools/ui-builder/project-migration.md]
Images are missing.
**line 17** : Sub list starts with `a`. 
**line 96** : Lines should be separated. `The uib_util_push_view() function is ...`
**line 105** : Lines should be separated. `The uib_view2_event_handler.c file is opened.`

[/native-tools/ui-builder/storyboard.md]
**line 86** : The fifth list item in git page is missing.

[/native-tools/ui-builder/ui-builder-conversion.md]
**line 126** : The spaces before the sentence looks wrong. This item is sub item of above list B. 
**line 140** : Sub items of the list should be separated
**line 152** and **line 163** : Lines should be separated. Also sub list items are merged as one line.
**line 184** : Link `passed from the UI Builder view system` not working
**line 217** : Broken link `Combining Screens from Multiple Applications`. It looks `project-migration.md` is correct

**Comment by ck11a** [comment]
**Adding newly found issues based on #200 (Commit id : "dae22e3f92")**

[/common-tools/dynamic-analyzer/overview.md]
All images in the file are broken.
 
[/common-tools/certificate-registration.md]
Web
 
[/common-tools/emulator-manager.md]
exporting an emulator  **(It does not jump to that content.)**
 
[/native-tools/ui-builder/component-attributes.md]
flipselector
 
[/native-tools/ui-builder/custom-ui-component.md]
EDC Editor
Group Block **(Linked to learn-edc-intro.md instead of learn-edc-group.md)**
 
[/native-tools/ui-builder/ui-builder-conversion.md]
Table: Window object components **(All links in the Table are broken.)**
 
[/native-tools/ui-builder/ui-builder.md
customized UI components
manage various data sources through   databinding
EDC Editor
 
[/tizen-studio/native-tools/coding.md]
UI Builder
 
[/native-tools/manifest-elements.md]
element hierarchy **(in label Element)**

**Comment by journey2w** [comment]
[/native-tools/ui-builder/multiple-screen.md]
line 15 : The sub list items are crumpled as one line. File types – images, EDJ, text, video, and audioStrings for localization => done
Also the separated lines in the note are merged as one line. When you support multiple screens....
line 71 : The separated lines are merged as one line. Landscape: ... and Portrait: ...
=> done
line 82 : Broken link Applications. It looks ../../../native/guides/app-management/applications.md is correct => done
line 85 : Broken link automatic scaling. It looks ../../../native/guides/ui/efl/multiple-screens.md is correct
=> done
line 101 : Broken link Localizing Applications. It looks ../po-file-editor.md is correct => done

line 149 : Lines should be separated. If there is no default resource, ... => Done

line 190 : Lines should be separated. Open the **Screen Configurator** window, ... => Done
line 194 : The list and sub list are broken. => done
line 219 : Lines should be separated. Open the **When the size of the UI component ... => Done

[/native-tools/ui-builder/project-migration.md] => combine-screens.md
Images are missing.
line 17 : Sub list starts with a. => done
line 96 : Lines should be separated. The uib_util_push_view() function is ... => done
line 105 : Lines should be separated. The uib_view2_event_handler.c file is opened. => done

[/native-tools/ui-builder/storyboard.md] => done
line 86 : The fifth list item in git page is missing.  => done

[/native-tools/ui-builder/ui-builder-conversion.md]  => convert-projects.md
line 126 : The spaces before the sentence looks wrong. This item is sub item of above list B. => done
line 140 : Sub items of the list should be separated => Done
line 152 and line 163 : Lines should be separated. Also sub list items are merged as one line. => done
line 184 : Link passed from the UI Builder view system not working => done
line 217 : Broken link Combining Screens from Multiple Applications. It looks project-migration.md is correct => done

**Comment by journey2w** [comment]
Fixed on #200 (Commit id : "dae22e3f92")

[/common-tools/dynamic-analyzer/overview.md]
All images in the file are broken. => done
 
[/common-tools/certificate-registration.md]
Web => done
 
[/common-tools/emulator-manager.md]
exporting an emulator  (It does not jump to that content.) => done
 
[/native-tools/ui-builder/component-attributes.md]
flipselector => done
 
[/native-tools/ui-builder/custom-ui-component.md]
EDC Editor => done
Group Block (Linked to learn-edc-intro.md instead of learn-edc-group.md) => done
 
[/native-tools/ui-builder/ui-builder-conversion.md]
Table: Window object components (All links in the Table are broken.) => No problem. They are links to API Ref.
 
[/native-tools/ui-builder/ui-builder.md] => already done
customized UI components
manage various data sources through databinding
EDC Editor
 
[/tizen-studio/native-tools/coding.md]
UI Builder => done
 
[/native-tools/manifest-elements.md]
element hierarchy (in label Element) => done
