### ISSUE TITLE
URL link error in /distribute

### ISSUE THREAD

**Issue by ck11a** [Samsung/tizen-docs#193]
[/how-to-distribute/overview.md]
Binary	
Application Title (Default Language) 
Binary File and Supported Device 
Expansion File Upload 
Validation Information
Sales
Country & Price 
Availability Date 
Category 
Age Restriction
Display
Application Detail 
Icon Image
Screenshots
YouTube URL 
Banner 
Support
Item	
In App Purchase Type & Item Group ID

[/validation/defects-tips/fail-install-execute-or-terminate-application.md]
this link

[/TOC.md]
Overview
Binary
Sales
Submit the Application
Item
Display
Application Validation Process

**Comment by journey2w** [comment]
[/how-to-distribute/overview.md] => done
Binary	
Application Title (Default Language) 
Binary File and Supported Device 
Expansion File Upload 
Validation Information
Sales
Country & Price 
Availability Date 
Category 
Age Restriction
Display
Application Detail 
Icon Image
Screenshots
YouTube URL 
Banner 
Support
Item	
In App Purchase Type & Item Group ID

[/validation/defects-tips/fail-install-execute-or-terminate-application.md]
this link => done

[/TOC.md] => done
Overview
Binary
Sales
Submit the Application
Item
Display
Application Validation Process

**Comment by ck11a** [comment]
[/how-to-distribute/overview.md]
Validation Information (It does not jump to that content.)
YouTube URL (It does not jump to that content.)

**Comment by journey2w** [comment]
Fixed on PR #214
