### ISSUE TITLE
Review result of /vstools

### ISSUE THREAD

**Issue by ck11a** [Samsung/tizen-docs#225]
**[/tools/certificate-manager.md]**
Line 4 : The following content is   missing. `You can use the Certificate Manager…`
Line 70 : The numbered list is incorrect.   `3. Click Finish` -> `5. Click Finish.`
 
**[/tools/dotnet-cli-ext.md]**
Line 305-315 : The lines in the   Sub-command should be merged into the `add [options]`.
Line 316-317 : The lines in the   Sub-command should be merged into the `list [options]`.
Line 318-319 : The lines in the   Sub-command should be merged into the `remove [options]`.
 
**[/tools/emulator-manager.md]**
Line 56 : The separated lines are merged   as one line. `To run the application faster…` and `The mobile emulator…`

**Comment by journey2w** [comment]
[/tools/certificate-manager.md]
Line 4 : The following content is missing. You can use the Certificate Manager… => There is no problem on the latest commit
Line 70 : The numbered list is incorrect. 3. Click Finish -> 5. Click Finish. => done
 
[/tools/dotnet-cli-ext.md]
Line 305-315 : The lines in the Sub-command should be merged into the add [options]. => => There is no problem on the latest commit.
Line 316-317 : The lines in the Sub-command should be merged into the list [options]. => There is no problem on the latest commit.
Line 318-319 : The lines in the Sub-command should be merged into the remove [options].
 
[/tools/emulator-manager.md]
Line 56 : The separated lines are merged as one line. To run the application faster… and The mobile emulator… => done

**Comment by journey2w** [comment]
Fixed on PR #230.
