### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by JINSEONGHUN** [Samsung/tizen-docs#25]
1. tizen-docs/docs/open-source-tizen/about/git-directory-structure.md
> https://github.com/Samsung/tizen-docs/blob/master/docs/open-source-tizen/developing/developing/installing.md

2. tizen-docs/docs/open-source-tizen/compliance/compliance-program.md
> https://github.com/Samsung/tizen-docs/blob/master/docs/open-source-tizen/compliance/compliance-specification.md

3. tizen-docs/docs/open-source-tizen/compliance/compliance-program.md
> https://github.com/Samsung/tizen-docs/blob/master/docs/open-source-tizen/compliance/compliance-specification.md

4. tizen-docs/docs/open-source-tizen/developing/building.md
> https://github.com/Samsung/tizen-docs/blob/master/docs/open-source-tizen/tools/gbs.md

5. tizen-docs/docs/open-source-tizen/developing/creating.md
> https://source.tizen.org/documentation/setting-development-environment

6. tizen-docs/docs/open-source-tizen/developing/creating.md
> https://source.tizen.org/documentation/installing-development-tools

7. tizen-docs/docs/open-source-tizen/developing/faq.md
> http://download.tizen.org/tools/openSUSE12.1/

8. tizen-docs/docs/open-source-tizen/tools/mic.md
> https://source.tizen.org/documentation/reference/mic-image-creator/faqs

9. tizen-docs/docs/open-source-tizen/tools/gbs/overview.md
> https://github.com/Samsung/tizen-docs/blob/master/docs/open-source-tizen/tools/developing/settingup.md

10. tizen-docs/docs/open-source-tizen/tools/gbs/overview.md
> https://github.com/Samsung/tizen-docs/blob/master/docs/open-source-tizen/tools/developing/installing.md

11. tizen-docs/docs/what-is-tizen/tizen.md
> https://github.com/Samsung/tizen-docs/blob/master/docs/what-is-tizen/what-is-tizen/mobile.md

12. tizen-docs/docs/what-is-tizen/tizen.md
> https://github.com/Samsung/tizen-docs/blob/master/docs/what-is-tizen/what-is-tizen/wearable.md

13. tizen-docs/docs/what-is-tizen/tizen.md
> https://github.com/Samsung/tizen-docs/blob/master/docs/what-is-tizen/what-is-tizen/tv

14. tizen-docs/docs/what-is-tizen/tv.md
> https://github.com/Samsung/tizen-docs/blob/master/docs/what-is-tizen/Smart-TVs-at-TDC2017_main_1.jpg

15. tizen-docs/docs/what-is-tizen/versions/tizen-4-0-m1.md
> https://github.com/Samsung/tizen-docs/blob/master/docs/what-is-tizen/versions/media/4.0_m1_announcement.jpg

16. tizen-docs/docs/what-is-tizen/versions/tizen-4-0-m1.md
>https://github.com/Samsung/tizen-docs/blob/master/docs/what-is-tizen/versions/media/4.0_plan.png

17. tizen-docs/docs/what-is-tizen/versions/tizen-4-0-m1.md
>https://github.com/Samsung/tizen-docs/blob/master/docs/open-source/release-notes/tizen-4-0-m1.md

18. tizen-docs/docs/TOC.md
> https://github.com/Samsung/tizen-docs/blob/master/docs/open-source-tizen/tools/gbs/usage.md

19. tizen-docs/docs/TOC.md
> https://github.com/Samsung/tizen-docs/blob/master/docs/open-source-tizen/tools/mic-image-creator.md

20. tizen-docs/docs/index.md
> https://bugs.tizen.org/jira

21. tizen-docs/README.md
> https://portal.tizen.org/docs

**Comment by journey2w** [comment]
#29 에서 이슈 해결함.

**Comment by journey2w** [comment]
#29 에서 이슈 해결함.
