### ISSUE TITLE
DOC Review Results

### ISSUE THREAD

**Issue by YoungdaeKoo** [Samsung/tizen-docs#26]
컨텐츠가 아직 수정 중인 것으로 보여, 현재까지 작성된 페이지별 내용 위주로 검토하였습니다.

[Tizen 4.0 M1]
"first milestone (M1) of Tizen 4.0 was released" 링크가 M2 링크로 연결
"Tizen 4.0 M1 announcement" 링크 깨짐 현상
"Tizen 4.0 M2 release plan" 링크 깨짐 현상
"Release Notes" 링크 깨짐 현상

[Tizen Wearable]
"Web Application" 링크가 "Native Application" 링크로 연결

[Tizen TV]
"Smart TV" 링크 깨짐 현상

[Git Directory Structure]
"Developing" 링크 깨짐 현상

[FAQ]
"http://download.tizen.org/tools/openSUSE12.1/" 링크 깨짐 현상
"http://www.example.com/latest/repos/oss/ia32/packages/repodata/repomd.xml" 링크 깨짐 현상

그 외에는 TOC의 폰트(Bold/Size)나 들여쓰기 등이 수정되어야 할 것 같습니다.

**Comment by journey2w** [comment]
일부는 제가 수정해서 https://github.com/Samsung/tizen-docs/pull/24 에서 merge 한 내용인 것 같습니다.
나머지도 확인해서 수정하겠습니다.

**Comment by YoungdaeKoo** [comment]
">>>"로 시작하는 라인에 현재 확인되는 현상을 기재하였습니다.
참고 부탁드립니다.

[Tizen 4.0 M1]
"first milestone (M1) of Tizen 4.0 was released" 링크가 M2 링크로 연결 => Tizen 4.0 M1의 release notes 제목이 잘못되어 수정했습니다.
  >>> 수정 확인
"Tizen 4.0 M1 announcement" 링크 깨짐 현상 => png file name 수정 완료
  >>> 해당 문구 삭제 여부 확인 필요
"Tizen 4.0 M2 release plan" 링크 깨짐 현상 => png fle name 수정 완료
  >>> 해당 문구 삭제 여부 확인 필요
"Release Notes" 링크 깨짐 현상 => Tizen 4.0 M1의 release notes 로 가는 link가 있어서 이 문구는 삭제하였습니다.
  >>> 삭제 확인

[Tizen Wearable]
 "Web Application" 링크가 "Native Application" 링크로 연결 => 수정 완료
  >>> 수정 확인

[Tizen TV]
 "Smart TV" 링크 깨짐 현상 => png file name 수정 완료
  >>> 링크 해제 여부 확인 필요

[Git Directory Structure]
 "Developing" 링크 깨짐 현상 => 왼쪽에는 TOC.md가 tree로 보이기때문에 Developing으로 가는 link를 줄 필요가 없어서 삭제했습니다.
  >>> 링크 깨짐 현상 재확인 필요

[FAQ]
"http://download.tizen.org/tools/openSUSE12.1/" 링크 깨짐 현상 => 내용을 Tools > GBS > FAQ로 이동 후에 수정 완료
  >>> Tools > GBS 하위에 FAQ 메뉴 확인 불가

"http://www.example.com/latest/repos/oss/ia32/packages/repodata/repomd.xml" 링크 깨짐 현상 => error message로 나오는 URL로 해당 사이트를 방문가 필요가 없습니다. 현상태 유지하겠습니다.
내용을 Tools > MIC > FAQ로 이동
  >>> Tools > MIC > FAQs 메뉴 링크 깨짐 현상

그 외에는 TOC의 폰트(Bold/Size)나 들여쓰기 등이 수정되어야 할 것 같습니다.
 => TOC.md 파일은 Docs 신규 사이트에서 LNB(Left Navigation Bar)를 만들기 위한 파일입니다.
4개의 depth를 #, ##, ###, ####로 구분하는 것이고 HTML H tag와 같은 역할은 하지 않습니다.
README.md 파일 참조
