### ISSUE TITLE
Review result of /dotnet/

### ISSUE THREAD

**Issue by mijin80lee** [Samsung/tizen-docs#289]
/dotnet/index.md
line 58: Add ','.( Android™ Windows Phone,)

/dotnet/guides/alarm/overview.md
Unnecessary page.

/dotnet/guides/alarm/alarms.md
line 28: H2 tag was not applied.
line 70: Code block was not applied.
line 154: H2 tag was not applied.

/dotnet/guides/app-management/app-icons.md
line 156: Change 'widgetshortcutinfo' to 'Widgetshortcutinfo'.

/dotnet/guides/app-management/data-control.md
line 3: General style sentence
line 35: Sentence diff. (change 'run' to 'involve')

/dotnet/guides/app-management/ui-app.md
line 227: Fill in the right value to 'Manifest file'

/dotnet/guides/app-management/watch-app.md
line 203: Note form was not applied.

/dotnet/guides/app-management/widget-app.md
line 86: Rewrite the code. ('WidgetDestroyType reason'to 'WidgetBase.WidgetDestroyType reason')
line 165,167: Same level with the line 145.
line 177,179: Same level with the line 145.

/dotnet/guides/connectivity/connection.md
line 59: The separated lines are merged as one line.

/dotnet/guides/connectivity/nfc.md
line 262,314,369,424,487,549,664,720,771: Remove 10 spaces.

/dotnet/guides/connectivity/telephony.md
line 185: Remove unnecessary line.
 
/dotnet/guides/connectivity/wifi.md
line 22: Table form need to be checked.

/dotnet/guides/internationalization/phonenumber.md
line 13: Add a space. (the regionusing the dash)

/dotnet/guides/location-sensors/device-sensors.md
line 5: The separated lines are merged as one line.
line 79: Add'.' at the end of sentence.
line 158: Rewrite 'timestamp' to 'timespan'. 
line 213: Rewrite 'timestamp' to 'timespan'. 
line 323: Rewrite 'timestamp' to 'timespan'. 

/dotnet/guides/location-sensors/geofences.md
line 61: Sentence diff need to be checked. (the default places, and Map)

/dotnet/guides/location-sensors/location.md
line 36: The separated lines are merged as one line.

/dotnet/guides/messaging/push-server.md
line 60: Change 'messages' to 'message'. (as the messages field)
line 110: Rewrite 'chuned' to 'chunked'.
line 120: Remove '**' before Table: Arguments.
line 124,125,126,127,128,129,130,131,132,133,134: The separated lines are merged as one line. 
line 223: Rewrite 'chuned' to 'chunked'.
line 329: Rewrite 'chuned' to 'chunked'.
line 472: Rewrite 'chuned' to 'chunked'.

/dotnet/guides/messaging/push.md
line 175(to the line 213): Change to the general contents style, Code tag was not applied.
line 177: Broken image. (![Push service state transitions](./media/push_state_transitions_cs.png))
line 187: Code block was not applied.
line 288: The separated lines are merged as one line.

/dotnet/guides/multimedia/camera.md
line 53: The separated lines are merged as one line.
line 56: Put this sentence into the note.
line 327: The separated lines are merged as one line.

/dotnet/guides/multimedia/image-barcode.md
line 46: Add 'n' in front of amespace. (Tizen.Multimedia.Vision amespaces in your application:)
line 274: Rewrite the 'Table: Supported barcode types', Broken images.
line 287: Rewrite the 'Table: Supported QR code specifications'.

/dotnet/guides/multimedia/media-content.md
line 677: The separated lines are merged as one line.
line 685: The separated lines are merged as one line.
line 701: The separated lines are merged as one line.

/dotnet/guides/multimedia/media-playback.md
line 314: The separated lines are merged as one line.

/dotnet/guides/multimedia/metadata.md
line 195: Remove 'strong tag **' before Table: Editable metadata attributes.
line 197: Remove '(https://developer.tizen.org/dev-guide/csapi/api/Tizen.Multimedia.MetadataEditor.html)'.
line 209: Code tag was not applied.
line 220: Remove 'strong tag **' before Table: Metadata extractor attributes.
line 229: The separated lines are merged as one line, Code tag was not applied
line 255: Fill in the right value.
line 256: Fill in the right value.

/dotnet/guides/notification/noti.md
line 47: Remove '{#quick_panel}'.
line 63: Remove '{#active_notification}'.
line 71: Remove '{#indicator}'.
line 79: Remove '{#lockscreen}'.
line 87: Remove '{#status_message}'.

/dotnet/guides/nui/NUIoverview.md
line 5: Change '2D or 3D' to 'two-dimensional or three-dimensional'.
line 18: Change '2D' to 'two-dimensional'.

/dotnet/guides/nui/animation-types.md
line 122: The separated lines are merged as one line.

/dotnet/guides/nui/button.md
line 8: Change 'Creating buttons' to 'Creating Buttons'.

/dotnet/guides/nui/flexcontainer.md
line 7: Change '"flex direction" is defined as *row*.' to **flex direction** is defined as **row**.'.
line 37: Change '"column"' to '**column**'.
line 44: Change '"column"' to '**column**'.
line 57: Change '"row"', '"center"' to '**row**', '**center**'.

/dotnet/guides/personal/account.md
line 26: The separated lines are merged as one line.
line 466,467,468,469,470: The separated lines are merged as one line.
line 494: The separated lines are merged as one line.

/dotnet/guides/personal/calendar.md
line 80,81: The separated lines are merged as one line.
line 86,87,88,89: The separated lines are merged as one line.
line 147,148: The separated lines are merged as one line.
line 226: Remove 'strong tag **' before Table: Event and instance example.
line 231,232: Fill in the right value.
line 256: Change '16^th^ to 17^th^, 17^th^' to ' 16th to 17th, 17th'.
line 263: Fill in the right value. 
line 482: Change '3^rd^, 4^th^, and 5^th^ day' to '3rd, 4th, and 5th day'.(ref.TD)
line 736: Remove the first '<br>'.

/dotnet/guides/personal/fido.md
line 5: Change 'a organization' to 'an organization'.

/dotnet/guides/text-input/input-method.md
line 69: Change'InputMethodContext id' to 'InputMethodContext ctx'.

/dotnet/guides/text-input/tts.md
line 544,556: Need to be checked. ('```')

/dotnet/guides/alarm/overview.md
Unnecessary Page. (Need to be checked.)

/dotnet/guides/data/data-cover.md
File name need to be changed to 'overview'.(Need to be checked.)

/dotnet/guides/internationalization
There's no overview page. ((Need to be checked.)

/dotnet/guides/location-sensors/location-sensors-cover.md
File name need to be changed to 'overview'.(Need to be checked.)

/dotnet/guides/media
Check the folder location.

/dotnet/guides/messaging/messaging-cover.md
File name need to be changed to 'overview'.(Need to be checked.)

/dotnet/guides/multimedia/media-cover.md
File name need to be changed to 'overview'.(Need to be checked.)

/dotnet/guides/notification/notification-cover.md
File name need to be changed to 'overview'.(Need to be checked.)

/dotnet/guides/nui/NUIoverview.md
File name need to be changed to 'overview'.(Need to be checked.)

/dotnet/guides/personal/personal-cover.md
File name need to be changed to 'overview'.(Need to be checked.)

/dotnet/guides/text-input/text-input-cover.md
File name need to be changed to 'overview'.(Need to be checked.)

**Comment by journey2w** [comment]
@JINSEONGHUN 
Please resolve this issue.

**Comment by mijin85cho** [comment]
Fixed by #300
