### ISSUE TITLE
DOC Review (in SE)

### ISSUE THREAD

**Issue by whatwant** [Samsung/tizen-docs#30]
수정을 반드시 해야한다는 의견은 아니고 참고 및 검토 요청드리는 내용으로 작성하였습니다.

**[ tizen-docs / docs / index.md ]**

Get Started with Tizen

More 링크가 있는데 "Installing Development Tools" 컨텐츠 하나만 있음
(tizen-docs / docs / open-source-tizen / developing / installing.md)

Get Started with Tizen .NET

링크 구성이 내부 문서들 間 링크와 developer 사이트의 문서들 링크들이 섞여 있음
앞 뒤로 있는 내용들과 달리 이 부분에만 동영상 등의 컨텐츠가 있다보니 조금 위화감이 있음
More 링크가 있는데 developer 사이트의 "What's New" 페이지로 링크(하나의 컨텐츠인데 More)

Get Started with Tizen Studio

"What is Tizen Application?" 링크를 누르면 developer 사이트의 "Introduction to Native Applications"으로 이동하게 되는데, 이보다는 "Overview" 페이지로 링크되는 것이 맞지 않나함
More 링크가 있는데 developer 사이트의 "Tizen Native API Guides" 페이지로 링크(전체 API도 아니고 Native API 하나의 컨텐츠로만 링크)

**Comment by journey2w** [comment]
Review 감사합니다.

1. Get Started with Tizen
More 링크가 있는데 "Installing Development Tools" 컨텐츠 하나만 있음
(tizen-docs / docs / open-source-tizen / developing / installing.md)
=> github에서 보면 installing.md로 가는데 이게 사이트에 publish가 되면 TOC.md 에 있는 Open Source Tizen Tree가 LNB에 펼쳐지고, Open Source Tizen > Developing > Installing Developing Tools (Developing의 첫 페이지)가 오른쪽에 보이게 됩니다. 그래서 link게 이렇게 동작하는 게 맞습니다.

Get Started with Tizen .NET

링크 구성이 내부 문서들 間 링크와 developer 사이트의 문서들 링크들이 섞여 있음
=> Tizen .NET은 developer.tizen.org로 모두 가게 되어 있습니다. 앞에 있는 Getting Started with Tizen은 내부인데, 이건 TD라는 것으로 이해하겠습니다. TD 문서를 다 가지고 오기 전까지는 이렇게 link를 제공할 수 밖에 었는데, 외부로 가는 것이라 걸 알 수 있도록 icon 같은 걸 추가하면 좋을 것 같기는 하겠네요.
아니면 TD로 가는 link 전체를 빼든지요..

앞 뒤로 있는 내용들과 달리 이 부분에만 동영상 등의 컨텐츠가 있다보니 조금 위화감이 있음
More 링크가 있는데 developer 사이트의 "What's New" 페이지로 링크(하나의 컨텐츠인데 More)
=> more는 Tizen .NET Preview의 가장 첫 페이지인 What's New로 이동하게 되어 있습니다. 더 보고 싶으면 다음 페이지로 Next 하면서 읽을 수 있습니다.

Get Started with Tizen Studio

"What is Tizen Application?" 링크를 누르면 developer 사이트의 "Introduction to Native Applications"으로 이동하게 되는데, 이보다는 "Overview" 페이지로 링크되는 것이 맞지 않나함
=> Overview로 link 가도록 수정하겠습니다.

More 링크가 있는데 developer 사이트의 "Tizen Native API Guides" 페이지로 링크(전체 API도 아니고 Native API 하나의 컨텐츠로만 링크)
=> 현재 TD의 구조상 API guides의 첫 페이지가 https://developer.tizen.org/development/guides 로 Tizen Native API Guides 입니다.

**Comment by journey2w** [comment]
Fixed at #35
