### ISSUE TITLE
open-source-tizen doc review

### ISSUE THREAD

**Issue by mijin80lee** [Samsung/tizen-docs#32]
**about** 

/conventions.md
1. With backslash: 하단 소스 박스 diff (줄바꿈필요)

/tizen-open-source-overview.md
1. 링크 확인 및 수정 필요(추후)
-https://www.tizen.org/user/register

**compliance**

/compliance-program.md
1. Tizen Compliance Tests (TCT) 링크 누락 to **tizen-docs/docs/open-source-tizen/compliance/compliance-test.md**
2. 링크 수정 필요?(추후)
-Tizen compliance mailing list
3. pdf 파일 안열림
-Tizen branding request form
-tizen_branding_request_form_for_tizen_mobile_profile_v1.0.pdf

/compliance-spec.md
1. pdf 파일 안열림
-Tizen 2.4 Compliance Specification for Mobile Profile (pdf)
-Tizen 2.3.1 Compliance Specification for Wearable Profile (pdf)
-Tizen 2.4 Compliance Specification for TV Profile (pdf)
-Tizen 3.0 Compliance Specification for IVI Profile (pdf)
-Tizen 3.0 Crosswalk Web Runtime API for IVI Profile (pdf)
-Tizen 3.0 Web Runtime Core Specification (pdf)
2. 링크 수정 필요?(추후)
-https://lists.tizen.org/listinfo/compliance

/compliance-test.md
1. Tizen Compliance Specification (TCS). 링크 수정요 
**from** tizen-docs/docs/open-source-tizen/compliance/compliance-spec.md 
**to** tizen-docs/docs/open-source-tizen/compliance/compliance-specification.md
2. Bill of Materials 내 image 앞 오타 '['삭제요
3. 링크 수정 필요?(추후)
-http://download.tizen.org/tct/

**developing**

/building.md
1. 기타 수정 필요 (tag노출)
-Excluding Specific Packages <a name="id3"></a>
-Speeding up a Local Build <a name-"speed"></a>
-Performing Another Build <a name="id4"></a>

/building-all.md
1. Replace the remote 'fetch url' in the _remote.xml~ 부분 rewriting 필요(소스box 구분없음)
2. 링크 수정 필요
-Tizen versions lower than Tizen 2.3, see Excluding Specific Packages.
**from** tizen-docs/docs/open-source-tizen/developing/build.md#id3 
**to** tizen-docs/docs/open-source-tizen/developing/building.md#id3
3. 기타 수정 필요 (tag노출)
-Cloning All Projects over SSH <a name="#over-ssh"></a>
-Cloning All Projects over HTTPS <a name="over-https"></a>
-GBS Build Concepts <a name="gbs-build-concepts"></a>

/contributing.md
1. 링크 수정 필요?(추후)
-http://download.tizen.org/releases/daily.
2. 소스box 수정 필요 (줄바꿈필요)
-Submit one of the packages in the group to create a tag: 이하
-Obtain the tag name from the output of the above command, 이하

/installing.md
1. 소스box 수정 필요 (줄바꿈필요)
-You can upgrade a development tool using one of following methods,이하 

/setting-up.md
1. 링크 수정 필요?(추후)
-Open the Register page
-"http://download.tizen.org/releases/daily/tizen/unified/"
2. 기타 수정 필요
-> [!Note] Using the GIT_AUTHOR_NAME
3. 소스box 수정 필요 (줄바꿈필요)
-Create a ~/bin/ subdirectory, incl 이하
-Set the GIT_PROXY_COMMAND and 이하

**porting**
비교 문서없이 각 page내에 링크 등 오류만 체크하였습니다.

/connectivity.md
1. 링크 오류
-http://hostap.epitest.fi/wpa_supplicant/

/graphics-and-ui.md
1. 링크 수정 필요?(추후)
-페이지 전체 https://review.tizen.org/xxx 링크

/kernel.md
1. 링크 수정 필요?(추후)
-Download the source from the u-boot-tm1 repository.(https://review.tizen.org/xxx)

/overview.md
1. 링크 수정 필요?(추후)
-You can get detailed information of the Tizen framework layer from Dev Guide[1] 

/telephony.md
1. 링크 수정 필요?(추후)
-Tizen source website http://review.tizen.org/git/

**release-notes**

/archives.md
1. 링크 수정 필요(all links to https://source.tizen.org/release/xxx)
-Tizen 2.3
-Tizen 2.2.1
-Tizen 2.2
-Tizen 2.1
-Tizen 2.0
-Tizen 1.0
-Tizen IVI 3.0 Milestones
-Tizen Common milestones

/tizen-2-3-1.md
1. 링크 수정 필요
-Getting source code
-Getting binaries and images
-Tizen 2.3.1 Release Notes

/tizen-2-4.md
1. 링크 수정 필요
-Getting source code
-Getting binaries and images
-Tizen 2.4 Release Notes

/tizen-3-0-m2.md
1. 전체내용 재확인 필요

/tizen-3-0-m3.md
1. 링크 수정 필요?(추후)
-Binaries for Tizen 3.0 M3 is here

/tizen-3-0-milestones.md
1. 링크 수정 필요?(추후)
-maintained in git of tizen.org.
-https://developer.tizen.org/development

/tizen-4-0-m1.md
1. 링크 수정 필요?(추후)
-http://download.tizen.org/services/archive/17.06/
-http://download.tizen.org/tools/archive/17.01.2/

**tizen-rt**

/rt-api.md
1. 링크 수정 필요?(추후)
-Public API
-Libs and Environment

/rt-getting-started.md
1. 기타 수정 필요
-Installing the GNU ARM Toolchain 에서 ※ The above command is an~ 는 다음 문장으로 변경 필요
-Getting Source Codes from Git에서 Run the following commands: 하위 내용 누락
-Building Tizen RT 하위 문장 전체 단락 재구분 필요
-Appendix A 하위 내용 누락
2. 링크 수정 필요?(추후)
-For list of supported boards and configuration sets, see Appendix A 

/rt-specification-1-0.md
1. 하위 문장 생략되어 해당 문장 추가 필요
-some advanced features are also included: 이하
-AraStorage also provides some advanced features, such as: 이하
-Tizen RT supports: 이하
-Services provided under Device Management can be broadly categorized into 4 types: 이하

**tools**

**gbs**

/gbs.conf.md
1. 소스box 수정 필요 (줄바꿈필요)
-Here's an example of configuration file: 이하
-Configuring Multiple Profiles 이하
-Here's an example of repository configuration specification: 이하
-Shell-Style Variable References: 이하
2. 링크 수정 필요?(추후)
-http://download.tizen.org/releases/daily/2.0alpha/common/latest/

/gbs-faq.md
1. 소스box 수정 필요 (줄바꿈필요)
-You can use this command:이하
-gbs chroot Related Issues 이하
2. 링크 수정 필요?(추후)
-http://download.tizen.org/tools/latest-release/openSUSE_13.2/,

/gbs-overview.md
1. Configuration File Overview 이하는 /gbs.conf.md 와 100% 동일 문서입니다. **확인 필요**

/gbs-usage.md
1. 링크 수정 필요?(추후) 
GBS provides several subcommands, including: 하위 링크 모두 https://source.tizen.org/xxx 로 향함.
-gbs-clone
-gbs-pull
-gbs-devel
-gbs-build
-gbs-remotebuild
-gbs-submit
-gbs-chroot
-gbs-import
-gbs-export
-gbs-changelog

**mic**

/mic-customize-image.md
1. 링크 404 error 및 수정 필요?(추후)
-http://download.tizen.org/releases/daily/trunk/ivi/latest/images/ivi-min... 
-http://download.tizen.org/snapshots/trunk/common/latest/repos/base/ia32/packages/repodata/. 
2. 소스box 수정 필요 (줄바꿈필요)
-Specify the repository 이하
-How to add / remove packages 이하
-Specify the post-scripts 이하

/mic-faq.md
1. 링크 수정 필요?(추후)
-https://bugs.tizen.org

/mic-overview.md
1. 링크 404 error 및 수정 필요
-Setup Development Environment pages. link to /docs/open-source-tizen/developing/setting-up.md
-FAQs from /docs/open-source-tizen/tools/mic/mic-reporting-issues.md 
to /docs/open-source-tizen/tools/mic/mic-faq.md
-Reporting Issues 
2. **Reporting Issues** 미작성? 확인 및 추가필요

/mic-usage.md
1. 링크 404 error 및 수정 필요?(추후)
-http://download.tizen.org/releases/daily/trunk/ivi/latest/images/ivi-min... 
2. 소스box 수정 필요 (줄바꿈필요)
-Create image-Basic usage 이하
-How to create an image 이하
-Chroot, Convert, How to set a proxy 이하

/gerrit-usage.md
1. 링크 수정 필요?(추후)
-or refer to the Gerrit Command Line

**Comment by journey2w** [comment]
어디서 테스트하신 것인지 모르겠지만, link 오류는 모두 잘못된 것 같습니다.

그리고 ex)로 제시하고 있는 http://download.tizen.org/releases/daily/trunk/ivi/latest/images/ivi-min... 는 URL이 없어도 됩니다. daily build하는 image는 몇일 것만 저장하고 있기때문에 날짜가 지나면 사라집니다.

**Comment by mijin80lee** [comment]
#33 과 동일합니다! 
말씀하신것처럼 live branch에서 review했으며 현재 link는 대부분 정상작동하지만,
링크 수정 필요?(추후) 라고 comment한 부분은 Developer.org 문서도 MD로 만들고, portal로 사이트도 개편이 되면, 추후에 링크 수정이 필요하다고 생각해서 issue 남긴 것입니다.
제 설명이 부족했던것 같습니다.

**Comment by journey2w** [comment]
TD 문서를 github으로 이관할 예정이기는 하지만 있지도 않은 페이지에 link를 걸 수는 없습니다.
현재 TD로 가는 문서에 대한 link는 TD 문서가 github으로 모두 이관된 후에 일괄적으로 link를 수정할 예정입니다. 그때 다시 opne해 주십시오.
