### ISSUE TITLE
URL link error in /native/tutorials, /native/getting-started, /web/tutorials and /web/getting-started

### ISSUE THREAD

**Issue by mijin80lee** [Samsung/tizen-docs#328]
/native/tutorials link error

1. /native/tutorials/details/event-handling.md
**see the Watch Application guide.**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/app-management/watch-app.md
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/app-management/ui-app/watch-app.md

2. /native/tutorials/details/sec-privileges.md
**privacy-related privileges can be resolved at runtime** 
https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/security/requesting-permissions.md
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/security/privacy-related-permissions.md

3. /native/tutorials/feature/app-connectivity-operation.md
**Tizen privileges, see Security and API Privileges.**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/tutorials/details/sec-privileges-n.md
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/tutorials/details/sec-privileges.md

4. /native/tutorials/feature/best-practice-battery.md
**see Application States and Transitions.**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/app-management/efl-ui-app.md#application-states-and-transitions
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/app-management/ui-app/efl-ui-app.md#application-states-and-transitions

5. /native/tutorials/process/app-dev-process.md
**in the User Interface guides.**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/ui/index.md
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/ui/overview.md

6. /native/tutorials/process/setting-properties.md
**You can describe the background category** 
https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/app-management/efl-ui-app.md#describing-the-background-category
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/app-management/ui-app/efl-ui-app.md#describing-the-background-category

7. /native/tutorials/ui-builder/ui-builder-app-design.md
**see Managing UI Component Attributes in layout.xml.**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/native-tools/component-attributes.md
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/native-tools/ui-builder/component-attributes.md

8. /native/tutorials/ui-builder/ui-builder-overview.md
**go to Introduction.**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/ui/efl/introduction.md
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/ui/efl/index.md

/native/getting-started link error

1. /native/getting-started/mobile/first-app.md
**download and install the Tizen Studio.**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/setup/download.md
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/setup/install-sdk.md
**the native tools included in the Tizen Studio** 
https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/native-tools/cover-native.md
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/native-tools/index.md
**using EFL.**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/ui/efl/introduction-n.md
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/ui/efl/index.md

2. /native/getting-started/wearable-watch/first-app-watch.md
**download and install the Tizen Studio.**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/setup/download.md
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/setup/install-sdk.md
**the native tools included in the Tizen Studio**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/native-tools/cover-native.md
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/native-tools/index.md
**use the Remote Device Manager** 
https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/getting-started/wearable/first-app-wn.md#remote_device
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/getting-started/wearable/first-app.md#target or make the new anchor with #remote_device.
**using EFL.**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/ui/efl/introduction.md
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/ui/efl/index.md

3. /native/getting-started/wearable-widget/first-app-widget.md
**download and install the Tizen Studio.**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/setup/download.md
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/setup/install-sdk.md
**the native tools included in the Tizen Studio**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/native-tools/cover-native.md
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/native-tools/index.md
**and draw the UI.**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/app-management/widget-app.md#get_window
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/app-management/ui-app/widget-app.md#get_window
**use the Remote Device Manager** 
https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/getting-started/wearable/first-app-wn.md#remote_device
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/getting-started/wearable/first-app.md#target or make the new anchor with #remote_device.
**using EFL.**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/ui/efl/introduction.md
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/ui/efl/index.md

4. /native/getting-started/wearable/first-app.md
**download and install the Tizen Studio.**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/setup/download.md
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/setup/install-sdk.md
**the native tools included in the Tizen Studio**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/native-tools/cover-native.md
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/native-tools/index.md
**using EFL.**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/ui/efl/introduction.md
to https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/ui/efl/index.md

**Comment by mijin80lee** [comment]
**download and install the Tizen Studio.**
@mijin85cho link recheck needed. 
Is it to https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/index.md ?

**Comment by mijin80lee** [comment]
/web/tutorials link error

1. /web/tutorials/sign-certificate.md
**see Working with the Certificate Profile.**
https://github.com/Samsung/tizen-docs/blob/master/docs/tizen-studio/common-tools/certificate-registration.md
https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/common-tools/certificate-registration.md


/web/getting-started link error

1. /web/getting-started/mobile/first-app.md
**the Web tools included in the Tizen Studio**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/web-tools/overview.md
https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/web-tools/index.md

2. /web/getting-started/wearable/first-app.md
the Web tools included in the Tizen Studio
https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/web-tools/overview.md
https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/web-tools/index.md

3. /web/getting-started/wearable-watch/first-app-watch.md
**the Web tools included in the Tizen Studio**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/web-tools/overview.md
https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/web-tools/index.md

4. /web/getting-started/wearable-widget/first-app-widget.md
**the Web tools included in the Tizen Studio**
https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/web-tools/overview.md
https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/web-tools/index.md

**Comment by mijin85cho** [comment]
Issue fixed by #335
