### ISSUE TITLE
what-is-tizen doc review

### ISSUE THREAD

**Issue by mijin80lee** [Samsung/tizen-docs#33]
/mobile.md
1. 링크 수정 필요 (추후), 
현재 모두 https://developer.tizen.org/xxx 으로 향함.
-Creating Mobile Native Applications
-Creating Web Native Applications
-Sample Mobile Native Applications
-Sample Mobile Web Applications
-Design Principles

/tizen.md
1. 링크 수정 필요 (추후)
-To facilitate developing Tizen applications, the **Tizen Studio**
-The **Tizen Store** is a marketplace of Tizen applications : tizen store도 링크 변경여부 확인필요

/wearable.md
1. 링크 수정 필요 (추후), 
현재 모두 https://developer.tizen.org/xxx 으로 향함.
-Creating Your First Wearable Native Watch Application
-Creating Your First Wearable Web Watch Application
-Native Application Samples
-Web Application Samples
-Design Principles

**Comment by journey2w** [comment]
link가 이상한 걸로 봐서는 github이나 browser가 이상한 것 같습니다. 
link가 모두 정상적으로 동작하고 있습니다.

확인을 위해 live branch에서 한번 더 테스트 부탁합니다.

**Comment by mijin80lee** [comment]
말씀하신것처럼 live branch에서 review했으며 현재 link는 모두 정상작동하지만, 
Developer.org 문서도 MD로 만들고, portal로 사이트도 개편이 되면, 
추후에 링크 수정이 필요하다고 생각해서 issue 남긴 것입니다. 
제 설명이 부족했던것 같습니다.

**Comment by journey2w** [comment]
TD 문서를 github으로 이관할 예정이기는 하지만 있지도 않은 페이지에 link를 걸 수는 없습니다.
현재 TD로 가는 문서에 대한 link는 TD 문서가 github으로 모두 이관된 후에 일괄적으로 link를 수정할 예정입니다. 그때 다시 opne해 주십시오.
