### ISSUE TITLE
Review result of /native

### ISSUE THREAD

**Issue by mijin80lee** [Samsung/tizen-docs#473]
/master/docs/application/native/tutorials/details/app-filtering.md
line138: The separated lines are merged as one line. (a.b.c.)
line187,188,189,190: Rearrange. (multimedia. ore multi_)
line191: Remove duplicate line.
line242(from242 to247): Remove lines related with IoT.
line278,279,280,281: Rearrange. (gyroscope, gyroscope., gyroscope_)
line366: Remove duplicate line.
line367,368,369,370,371: Rearrange. (multimedia. ore multi_)
line446,447,448,449: Rearrange. (gyroscope, gyroscope., gyroscope_)

/master/docs/application/native/tutorials/details/sec-privileges.md
line120: Contents diff. Check the Tizen Developer site. (LAC (Location Area Code), and TAC (Tracking Area Code))

/master/docs/application/native/tutorials/feature/app-contacts-management.md
line39,40: Add 1 space at the beginning.

/master/docs/application/native/tutorials/process/debugging-app.md
line20,21: The separated lines are merged as one line. (Executes the current line)

/master/docs/application/native/tutorials/process/performance.md
line311: Check code tag. (__libc_freeres())
line346: The separated lines are merged as one line. (The named method is only)

/master/docs/application/native/tutorials/process/setting-properties.md
line169: The separated lines are merged as one line. (To define the kind)
line210: The separated lines are merged as one line. (This is a mandatory property.)
line212: The separated lines are merged as one line. (This is a mandatory property.)
line216: The separated lines are merged as one line. (Capabilities are defined)
line236: The separated lines are merged as one line. (This is a mandatory property.)

/master/docs/application/native/guides/alarm/alarms.md
line32: Remove 2 spaces at the end.
line33: Remove 3 spaces at the end and only 3 spaces from the beginning.
line34: Remove 1 space at the beginning.

/master/docs/application/native/guides/alarm/trigger.md
line165,167: The separated lines are merged as one line. (It denotes logical)

/master/docs/application/native/guides/app-management/ui-app/watch-app.md
line97(from97 to103): Remove 1 space at the beginning.
line107(from107 to112): Remove 1 space at the beginning.
line116(from116 to121): Remove 1 space at the beginning.
line125(from125 to130): Remove 1 space at the beginning.
line134(from134 to138): Remove 1 space at the beginning.
line142(from142 to147): Remove 1 space at the beginning.

/master/docs/application/native/guides/app-management/ui-app/dali-widget-app.md
line53: Contents diff. Check the Tizen Developer site. (to widget viewer application)

/master/docs/application/native/guides/app-management/common-appcontrols.md
line1137: The separated lines are merged as one line. (1.You can execute, 2.For example)
line1172: Contents diff. Check the Tizen Developer site. (This key is optional and supported since Tizen 4.0)
line1898: Fill in the blank Note Column. (This key is optional.)

/master/docs/application/native/guides/app-management/package-manager.md
line103: The separated lines are merged as one line. (This function fills)
 
/master/docs/application/native/guides/app-management/data-bundles.md
line114,115: Remove 3 spaces at the beginning.
line115: Add blank line.

/master/docs/application/native/guides/ui/efl/container-layout.md
line160: Check note form.

/master/docs/application/native/guides/ui/efl/efl-util.md
line192,193: Remove 1 space at the beginning.

/master/docs/application/native/guides/internationalization/i18n.md
line78: The separated lines are merged as one line. (Managing date intervals)
line316: Change 2 to two.
line408: Contents diff. Check table form. (Either a or b)
line491: Add 1 apace. ((in mobile and wearableapplications))
line643: Contents diff. Check table form. (Table: Digit shaping option combinations)
line855: The separated lines are merged as one line. (Syntax:)
line1552: Remove the blank line.
line1586: Contents diff. Check the Tizen Developer site. (To check whether)
line2074: Contents diff. Check the Tizen Developer site. (Check whether)

/master/docs/application/native/guides/internationalization/resource-localization.md
line149: Contents diff. Check the Tizen Developer site. (HTML's \&nbsp;\)

/master/docs/application/native/guides/graphics/cairo.md
line256: Remove all spaces. 
(cairo_surface_t *source = cairo_image_surface_create_for_data(src_buffer, CAIRO_FORMAT_ARGB32, w, h, evas_object_image_stride_get(decoded_img));)

/master/docs/application/native/guides/multimedia/media-content.md
Check all space in code block. 

/master/docs/application/native/guides/multimedia/image-edit.md
line220: The separated lines are merged as one line. (If hardware acceleration)

/master/docs/application/native/guides/multimedia/image-barcode.md
line203(from203 to217): Contents diff. Check the code block.
line223(from223 to230): Contents diff. Check the code block.

/master/docs/application/native/guides/multimedia/media-controller.md
line28: Add ',' before and. (the client side and)
line42: Add ',' before and. (the server side and)
line44: Add ',' before and. (the client side and)
line109: Add ',' before and. (mc_server_set_XXX() and)
line111: Add ',' before and. (mc_server_set_playback_state() and)
line182: Add ',' before and. (mc_server_add_item_to_playlist() and)

/master/docs/application/native/guides/connectivity/nfc.md
line1110: The separated lines are merged as one line.
line1115: The separated lines are merged as one line.
line1118: Add 1 space before operation. (operation is launching.)
line1122: The separated lines are merged as one line.

/master/docs/application/native/guides/connectivity/iotcon.md
line126: Add 1 space. (and wearableapplications)

/master/docs/application/native/guides/messaging/push-server.md
line667: Check the code tag error.
line671: Check the code tag error.

/master/docs/application/native/guides/location-sensors/maps.md
line863: Remove \` at the end. (/* Error handling */\`\)

/master/docs/application/native/guides/location-sensors/device-sensors.md
line294: The separated lines are merged as one line. (Max. value = 19.6)
line295: The separated lines are merged as one line. (Max. value = 19.6)
line296: The separated lines are merged as one line. (Max. value = 19.6)
line549: Remove '()'.
line674: The separated lines are merged as one line. (Max. value = 100)

/master/docs/application/native/guides/data/data-storages.md
line35: Add 1 space before function. (function excludes)
line49: Add 1 space before function. (function excludes)
line173: Add 1 space before and. (storage_get_internal_memory_size()and)

/master/docs/application/native/guides/device/system.md
line206: Contents diff. Change '.'. to ':' at the end.
line216: Contents diff. Change '.'. to ':' at the end.

/master/docs/application/native/guides/compliations/watchface-complication.md
line30(from30 to44): Fill in the blank.

/master/docs/application/native/guides/compliations/watchface-complication-provider.md
line127: Contents diff. (complication provider)
line131(from131 to150): Check the code block.
line183(from183 to197): Fill in the blank.

**Comment by mijin85cho** [comment]
Hello, @mijin80lee
I raised #516 to fix this issue.
Would you please review the update?

**Comment by mijin80lee** [comment]
@mijin85cho Okay, I'm gonna tell you if there are issues.

**Comment by mijin85cho** [comment]
/master/docs/application/native/guides/internationalization/i18n.md
line408: Contents diff. Check table form. (Either a or b)
	**-> It works well on https://docs.stg.tizen.org/application/native/guides/internationalization/i18n#formal-syntax**
line643: Contents diff. Check table form. (Table: Digit shaping option combinations)
	**-> It works well on https://docs.stg.tizen.org/application/native/guides/internationalization/i18n#arabic-character-shaping-with-ushape**

/master/docs/application/native/guides/multimedia/image-barcode.md
line203(from203 to217): Contents diff. Check the code block.
	-**> It works well on https://github.com/Samsung/tizen-docs/commit/04f8f0f4218f06a95e3b913bce849a738b5d5b75#diff-0804fd36e9f500c21af4b3d270ad7753**
line223(from223 to230): Contents diff. Check the code block.
	**-> Updated contents when the md file is created.**

/master/docs/application/native/guides/messaging/push-server.md
line667: Check the code tag error.
line671: Check the code tag error.
	**-> It works well on https://docs.stg.tizen.org/application/native/guides/messaging/push-server**
		
/master/docs/application/native/guides/compliations/watchface-complication.md
line30(from30 to44): Fill in the blank.
	**-> It would be better not to fill the blank. The second and third columns are not related, so filling it can cause confusion.**

/master/docs/application/native/guides/compliations/watchface-complication-provider.md
line127: Contents diff. (complication provider)
	-> TD is correct
line183(from183 to197): Fill in the blank.
	**-> It would be better not to fill the blank. The second and third columns are not related, so filling it can cause confusion.**


**Additional fixes**
docs/application/native/guides/ui/dali/videoview.md 
docs/application/native/guides/connectivity/softap.md 
docs/application/native/guides/multimedia/audio.md (deleted)
docs/application/native/guides/ui/efl/wearable/ui-components.md
/docs/application/native/guides/multimedia/thumbnail-images.md

**Comment by mijin80lee** [comment]
@mijin85cho 
Thank you for the explanation above. 
And I reviewed all of #516 and approved it.
