### ISSUE TITLE
Review result of /web, /dotnet

### ISSUE THREAD

**Issue by mijin80lee** [Samsung/tizen-docs#477]
/master/docs/application/web/getting-started/wearable/first-app.md
line270(from270 to284): Contents diff. Check this code block. 

/master/docs/application/web/getting-started/wearable-watch/first-app-watch.md
line270(from270 to287): Contents diff. Check this code block. 

/master/docs/application/web/tutorials/process/setting-properties.md
line173: Add 1 space. (the URLsub-domains)
line211: Remove 1 space. (href=" http://)
line221: Contents diff. Check the Tizen Developers. ((in mobile, wearable, and TV applications))

/master/docs/application/web/guides/app-management/web-widget.md
line337: Remove 3 spaces at the end.
line673(from673 to675): Remove 2 spaces in the beginning.
line749(from749 to761): Remove 2 spaces in the beginning.

/master/docs/application/web/guides/app-management/preference.md
line45: Remove 3 spaces at the end.

/master/docs/application/web/guides/app-management/app-info-control.md
Contents diff. Check the Tizen Developers.

/master/docs/application/web/guides/cordova/core.md
line31,32: Add 1 space in the beginning.

/master/docs/application/web/guides/cordova/file.md
line106: Remove 3 spaces at the end.

/master/docs/application/web/guides/cordova/network-information.md
line95: Remove 3 spaces at the end.

/master/docs/application/web/guides/tau/helper.md
line122,123: Add 1 space in the beginning.
line125,126: Add 1 space in the beginning.

/master/docs/application/web/guides/tau/globalization.md
line119,120,121: Check the space in the table. (Table: CLDR requirements)
line138: Check the space.Remove unnecessary spaces. (});)
line154: Check the space.Remove unnecessary spaces. (});)
line169: Check the space.Remove unnecessary spaces. (});)
line184: Check the space.Remove unnecessary spaces. (ko.json)
line211: Check the space.Remove unnecessary spaces. (})
line226: Check the space.Remove unnecessary spaces. (});)
line242: Check the space.Remove unnecessary spaces. (})
line261: Check the space.Remove unnecessary spaces. (});)

/master/docs/application/web/guides/tau/tau-porting.md
Check the space. Remove unnecessary spaces after all \</scipt>.
line323,334: Check the space. Remove unnecessary spaces after all \</ul>.

/master/docs/application/web/guides/alarm/alarms.md
line3: Contents diff. Check the Tizen Developers. (You can schedule)

/master/docs/application/web/guides/multimedia/audio.md
line43: The separated lines are merged as one line. (The following example)

/master/docs/application/web/guides/connectivity/iotcon.md
line42,43,44: Remove 1 space in the beginning.

/master/docs/application/web/guides/connectivity/nfc.md
line99,100: Remove 1 space in the beginning.

/master/docs/application/web/guides/data/file-system.md
line10: Contents diff. Check the Tizen Developers. (on all mobile, wearable, and TV devices)

/master/docs/application/web/guides/data/file-archiving.md
line31(from31 to34): Check the space.Remove unnecessary space. 

/master/docs/application/web/guides/security/tee-client.md
line49: Missing code block. Contents diff. Check the tizen developers.
 
/master/docs/application/web/guides/w3c/device/touch.md
line97(from97 to102): Add 1 space in the beginning.

/master/docs/application/web/guides/w3c/storage/indexdb.md
line101: The separated lines are merged as one line. (object store.The)

/master/docs/application/web/guides/w3c/perf-opt/performance-guide.md
line19: Contents diff. Check the Tizen Developers. 
line21: Contents diff. Check the Tizen Developers. 

/master/docs/application/web/guides/w3c/supplement/webgl.md
line567,568: Remove 1 space in the beginning.

/master/docs/application/web/guides/w3c/ui/ui-layout.md
line340: Contents diff. Check the Tizen Developers. (Table: Tizen specialized media feature)

/master/docs/application/dotnet/getting-started/mobile/first-app.md
line377(from377 to383): Remove 4 spaces in the beginning.
line389(from389 to397): Remove 4 spaces in the beginning.
line404(from404 to408): Remove 4 spaces in the beginning.
line416(from416 to432): Remove 4 spaces in the beginning.

/master/docs/application/dotnet/tutorials/certificates/permit-device-to-install-apps.md
line12: The separated lines are merged as one line. (If the certificate)

/master/docs/application/dotnet/guides/index.md
line8: The separated lines are merged as one line. (For the full specification)
line44: Contents diff. Check the Tizen Developers.
line48(from48 to 60): Contents diff. Check the Tizen Developers.
line79: Contents diff. Check the Tizen Developers.(Alarms and Scheduling)

/master/docs/application/dotnet/guides/app-management/app-icons.md
line156: Contents diff. (Widgetshortcutinfo shortcut = new Widgetshortcutinfo)

/master/docs/application/dotnet/guides/alarm/alarms.md
line84: Remove 1 space in the beginning.

/master/docs/application/dotnet/guides/connectivity/nfc.md
line262: Remove 10 spaces in the beginning.
line314: Remove 10 spaces in the beginning.
line369: Remove 10 spaces in the beginning.
line424: Remove 10 spaces in the beginning.
line487: Remove 10 spaces in the beginning.
line549: Remove 10 spaces in the beginning.
line664: Remove 10 spaces in the beginning.
line720: Remove 10 spaces in the beginning.
line771: Remove 10 spaces in the beginning.

/master/docs/application/dotnet/guides/location-sensors/geofences.md
Contents diff. (my places or my Places?)

/master/docs/application/dotnet/guides/personal/calendar.md
line263: Contents diff. Check the Tizen Developers.

/master/docs/application/dotnet/guides/nlp/overview.md
line5: Contents diff. (DOTNET applications or .NET applications)

**Comment by mijin85cho** [comment]
Hello, @mijin80lee
I raised #526 to fix this issue.
Would you please review the update?

**Comment by mijin80lee** [comment]
@mijin85cho Okay, I'm gonna tell you if there are issues.

**Comment by mijin85cho** [comment]
Below are comments for some not-fixed files.


/master/docs/application/web/tutorials/process/setting-properties.md
line221: Contents diff. Check the Tizen Developers. ((in mobile, wearable, and TV applications))
	**=> md version is correct. TD should be fixed.**
line150: Contents diff. Check the Tizen Developers. ((in mobile and TV applications))
	**=>  md version is correct. TD should be fixed.**

/master/docs/application/web/guides/app-management/app-info-control.md
Contents diff. Check the Tizen Developers.
	**=> I can't get the location of this file. Would you please re-check?**

/master/docs/application/web/guides/alarm/alarms.md
line3: Contents diff. Check the Tizen Developers. (You can schedule)
	**=> md version is correct. TD should be fixed.**

/master/docs/application/web/guides/data/file-system.md
line10: Contents diff. Check the Tizen Developers. (on all mobile, wearable, and TV devices)
	**=> md version is correct. TD should be fixed.**

/master/docs/application/web/guides/data/file-archiving.md
line31(from31 to34): Check the space.Remove unnecessary space.
	**=> Sorry, I don't see the unnecessary spaces in the content of the table.**
	    **The space generated is related with the "table" style of the md.**
                **Am I missing any point?**

/master/docs/application/web/guides/w3c/perf-opt/performance-guide.md
line19: Contents diff. Check the Tizen Developers.
line21: Contents diff. Check the Tizen Developers.
	**=> Restructuring result which is done during md converting. However we don't need to apply this fix on TD.
 	=> I just fixed the broken link.**

/master/docs/application/web/guides/w3c/ui/ui-layout.md
line340: Contents diff. Check the Tizen Developers. (Table: Tizen specialized media feature)
	**=> Github issue. It works well on https://docs.stg.tizen.org/application/web/guides/w3c/ui/ui-layout.**

/master/docs/application/dotnet/guides/alarm/alarms.md
line84: Remove 1 space in the beginning.
	**=> Sorry, I can't get the point.**

/master/docs/application/dotnet/guides/index.md
	**=> Fixed by other PR**


**Just for check**
/master/docs/application/web/guides/app-management/web-widget.md
	**-> Would you please check the location of this file? It looks like the location is changed.**

**Comment by mijin80lee** [comment]
/master/docs/application/web/tutorials/process/setting-properties.md
 line221: Contents diff. Check the Tizen Developers. ((in mobile, wearable, and TV applications))
=> md version is correct. TD should be fixed.
**fixed.**
 line150: Contents diff. Check the Tizen Developers. ((in mobile and TV applications))
=> md version is correct. TD should be fixed.
**fixed.** 

/master/docs/application/web/guides/app-management/app-info-control.md
 Contents diff. Check the Tizen Developers.
=> I can't get the location of this file. Would you please re-check?
**I think Menu tree for Github and TD is different. So, no issues more.**  


/master/docs/application/web/guides/alarm/alarms.md
 line3: Contents diff. Check the Tizen Developers. (You can schedule)
=> md version is correct. TD should be fixed.
**fixed.**

/master/docs/application/web/guides/data/file-system.md
 line10: Contents diff. Check the Tizen Developers. (on all mobile, wearable, and TV devices)
=> md version is correct. TD should be fixed.
**fixed.**

/master/docs/application/web/guides/data/file-archiving.md
 line31(from31 to34): Check the space.Remove unnecessary space.
=> Sorry, I don't see the unnecessary spaces in the content of the table.
The space generated is related with the "table" style of the md.
Am I missing any point?
**I think it's because of the blank in front of <br> in the table.**

/master/docs/application/web/guides/w3c/perf-opt/performance-guide.md
 line19: Contents diff. Check the Tizen Developers.
 line21: Contents diff. Check the Tizen Developers.
=> Restructuring result which is done during md converting. However we don't need to apply this fix on TD.
 => I just fixed the broken link.
**okay.**

/master/docs/application/web/guides/w3c/ui/ui-layout.md
 line340: Contents diff. Check the Tizen Developers. (Table: Tizen specialized media feature)
=> Github issue. It works well on https://docs.stg.tizen.org/application/web/guides/w3c/ui/ui-layout.
**okay.**

/master/docs/application/dotnet/guides/alarm/alarms.md
 line84: Remove 1 space in the beginning.
=> Sorry, I can't get the point.
**Sorry no issues.**

/master/docs/application/dotnet/guides/index.md
=> Fixed by other PR
**okay.**

Just for check
 /master/docs/application/web/guides/app-management/web-widget.md
-> Would you please check the location of this file? It looks like the location is changed.
**Is this present location, right? docs/application/web/guides/applications/web-widget.md**

**Comment by mijin85cho** [comment]
Thanks for the check & updates.

/master/docs/application/web/guides/app-management/web-widget.md
-> Would you please check the location of this file? It looks like the location is changed.
Is this present location, right? docs/application/web/guides/applications/web-widget.md
**-->Yes, it looks so. So the "web/guides/applications/web-widget.md" file is edited based on the review comment for "web/guides/app-management/web-widget.md".**
