### ISSUE TITLE
We need another PR for reviewing source.tizen.org docs. 

### ISSUE THREAD

**Issue by journey2w** [Samsung/tizen-docs#54]
@MariLB and @l10nbridge 

PR #48 & PR #52 were merged.
When you push new commit to apply to our review comment, please pull the latest the original repo and then work.

**Comment by l10nbridge** [comment]
Please clarify:

You have closed #48, #49 and #50.
Every single one of those has open queries that you have not answered at all.
And they have some query answers from you, which are not clear and require further clarifications, but we had no time to ask for those before you closed them.
How do you want us to deal with those? Should we open a new issue and list all the open problems there?

#48 was closed, and now some additional changes related to that are being handled in #53.
However, are you saying that we need to continue work with your review comments based on the merged original repo content, and not the #53 content?

**Comment by journey2w** [comment]
Please open  a new issue for unanswered queries and see the style guide.
If you can't know how to change docs and which markdown styles apply to some elements, please keep the base docs.
