### ISSUE TITLE
Tizen 5.5 M1 release: Please append nnstreamer feature 

### ISSUE THREAD

**Issue by leemgs** [Samsung/tizen-docs#738]
It is strange. I could not find the nnstreamer feature for on-device AI at #PR721 to generate Tizen 5.5 M1 release note. We need to append the nnstreamer feature at Tizen 5.5 M1 release note. I commented on the details of the nnstreamer at the below PR #721. 

**Comment**
* https://github.com/Samsung/tizen-docs/pull/721/files#r289219796

**NNStreamer: Neural Network Streamer for On Device AI**
```bash
- nnstreamer: Neural Network Streamer
  - Added an efficient and flexible stream pipeline to neural networks.
  - Support a neural network model as a media filter and converter.
  - Support multiple neural network models in a single stream pipeline instance.
  - Support multiple sources and stream paths for neural network models.
  - Support RNN and CNN model architectures with Tensorflow, Tensorflow-lite.
  - Added neural network API based on NNStreamer to manage pipelines.
  - Added a plugin to support Linux IIO based sensors.
```

\CC: @myungjoo @jijoongmoon @again4you @jaeyun-jung @leemgs @wooksong @helloahn @kparichay @dongju-chae

**Comment by leemgs** [comment]
* Status report:
강영애님 + 김석원님 are going to add the NNStreamer feature to the 5.5 M1 release note. 
Thanks. 😄

**Comment by leemgs** [comment]
Completed. 

* https://developer.tizen.org/tizen/release-notes/tizen-5.5-public-m1

![image](https://user-images.githubusercontent.com/82404/58674833-96ca2100-838c-11e9-8bd6-bb2825408654.png)

**Comment by mijin85cho** [comment]
Thanks for the checking.
