### ISSUE TITLE
Open issues from earlier review rounds

### ISSUE THREAD

**Issue by l10nbridge** [Samsung/tizen-docs#81]
In the master branch:

- docs/TOC.md:
  Is the location of the "open-source-tizen/porting/maintenance-models.md" topic correct in the TOC? It is currently located within the porting guides, but should it be moved to the “Developing” section? 
- The "docs/open-source-tizen/compliance/media/tizen_branding_request_form_for_tizen_mobile_profile_v1.0_1.pdf" file is corrupted and does not open. Please push in a corrected file version.

In the vs-tools-tizen branch:

- docs/vs-tools-tizen/tools/ profiler-user-manual.md:
In the “Recording Profiling Sessions" section, the screenshot shows a “Trace Garbage Collection” option. However, it is not explained within the bullet list below the screenshot, like all the other options. Please add an explanation.

**Comment by journey2w** [comment]
Resolved: PR #89
