### ISSUE TITLE
onevent method does not return the correct object

### ISSUE THREAD

**Issue by adiesel** [Samsung/tizen-docs#822]
Hello.

We try to use the method: _**onevent**_, documented here, but, every time he is called the return contains only a string with a description.
Like this:
_**PLAYER_MSG_BITRATE_CHANGE**_

In the documentation, the return should contain an object, but, it's not true in our tests.

We will want to know: how get the value associated with this event?

```
The code:

const listener = {
      onevent: (...param) => {
            console.log(param)
      }
}

this.avplay.setListener(listener)
```
We would like to get: bitrate and resolution. =T
You can help us?

**Comment by journey2w** [comment]
@adiesel 
I don't find out PLAYER_MSG_BITRATE_CHANGE and onevent in our documents.
Could you let me know the document(file name)?

Do you want to know how to get bitrate and resolution using ContentManager Web API?
Did you see the tizen-docs/docs/application/web/api/latest/device_api/mobile/tizen/content.html?
If so, I will forward your question to the module owner.

**Comment by journey2w** [comment]
@adiesel 
I found out AVPlay API on 
https://developer.samsung.com/tv/develop/api-references/samsung-product-api-references/avplay-api/.
AVPLay API is not Tizen standard API but a product API for TV.  

Please raise a question on https://developer.samsung.com/forum/en?boardName=SDK&searchSubIdAll=&searchSubId=0000000102&topCtgy=06&searchType=ALL&searchText=.
