### ISSUE TITLE
Windows CLI?

### ISSUE THREAD

**Issue by UltraCakeBakery** [Samsung/tizen-docs#963]
Tizen provides a CLI for windows but it's not used anywhere in the docs.

**Comment by journey2w** [comment]
Hello @UltraCakeBakery,
Tizen provides two kinds of CLI: SDB and Tizen Studio CLI. You can see the guides on the following pages:
- SDB: https://docs.tizen.org/application/tizen-studio/common-tools/smart-development-bridge
- Tien Studio CLI: https://docs.tizen.org/application/tizen-studio/common-tools/command-line-interface

If they are not what you find, please get back to me.

**Comment by UltraCakeBakery** [comment]
^ was not what I was looking for. I recommend anyone who wants to deal with tizen to just fucking don't. It sucks and is a maintenance nightmare.
